### ISSUE TITLE
Lumen 5.3 error! with PHP-7.1.5

### ISSUE THREAD

**Issue by DarthPestilane** [vyuldashev/laravel-queue-rabbitmq#132]
lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function PhpAmqpLib\Wire\bcadd() in /var/www/html/ibupro-cloud/item/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php:274

**Comment by DarthPestilane** [comment]
using php docker image: php:7.1.5-fpm-alpine

**Comment by vyuldashev** [comment]
Install bcmath php extension.

**Comment by DarthPestilane** [comment]
My bad.
