### ISSUE TITLE
Intermittently failed connection - how do we handle these?

### ISSUE THREAD

**Issue by CmdrSharp** [vyuldashev/laravel-queue-rabbitmq#137]
We're intermittently seeing messages like the below in our logs. Is there a way to handle these natively within the extension? If so, can you provide any resource to help us on our way?
It doesn't appear to (though we're having trouble verifying that) re-try the queuing automatically.

This happens upon reading the queue as well, again randomly. At that point however I'd wager it does re-try as that job wouldn't be lifted from the queue to begin with.

`
 ErrorException: fwrite(): send of 340 bytes failed with errno=104 Connection reset by peer in /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:281
Stack trace:
#0 [internal function]: PhpAmqpLib\Wire\IO\StreamIO->error_handler(8, 'fwrite(): send ...', '/home/forge/ome...', 281, Array)
#1 /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(281): fwrite(Resource id #358, '\x01\x00\x00\x00\x00\x01L\x00\n\x00\v\x00\x00\x00\xF3...', 8192)
#2 /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(327): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x00\x00\x00\x01L\x00\n\x00\v\x00\x00\x00\xF3...')
#3 /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(448): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x00\x00\x00\x01L\x00\n\x00\v\x00\x00\x00\xF3...')
#4 /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(230): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(0, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#5 /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(797): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#6 /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(206): PhpAmqpLib\Connection\AbstractConnection->x_start_ok(Array, 'AMQPLAIN', '\x05LOGINS\x00\x00\x00\x05omeg...', 'en_US')
#7 /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(180): PhpAmqpLib\Connection\AbstractConnection->connect()
#8 /home/forge/xxxxxxx/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(59): PhpAmqpLib\Connection\AbstractConnection->__construct('omega', 'DenyPRWE33wuzS8...', '/omega', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#9 /home/forge/xxxxxxx/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/VladimirYuldashev/LaravelQueueRabbitMQ/Queue/Connectors/RabbitMQConnector.php(29): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('epsilon.int.rel...', '5672', 'omega', 'DenyPRWE33wuzS8...', '/omega')
#10 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(154): VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Connectors\RabbitMQConnector->connect(Array)
#11 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(135): Illuminate\Queue\QueueManager->resolve('rabbitmq')
#12 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(217): Illuminate\Queue\QueueManager->connection('rabbitmq')
#13 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->runNextJob('rabbitmq', 'status', Object(Illuminate\Queue\WorkerOptions))
#14 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('rabbitmq', 'status')
#15 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#16 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#17 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#19 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#20 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#21 /home/forge/xxxxxxx/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 /home/forge/xxxxxxx/vendor/symfony/console/Application.php(869): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/forge/xxxxxxx/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/forge/xxxxxxx/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/forge/xxxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/forge/xxxxxxx/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 {main}  
`

Any insight would be appreciated!

**Comment by CmdrSharp** [comment]
The other error we intermittently get (equal to this one) is:
PhpAmqpLib\Exception\AMQPRuntimeException: Broken pipe or closed connection

**Comment by vyuldashev** [comment]
Seems like the problem with your RabbitMQ instance itself.

**Comment by CmdrSharp** [comment]
It's difficult to say whether the problem is with the RabbitMQ instance - but regardless, the question at hand is how we can deal with a potentially broken connection.
Would placing the dispatching of the job within a try-catch, catching AMQPRuntimeException, give us the ability to handle it perhaps?

**Comment by CmdrSharp** [comment]
Currently attempting a few possible solutions after some looking around. Some suggest that the issue lies with the prefetch count being too high - others mean that the connection timeout needs to be increased. I'm attempting the latter part first, by modifying the connection to have a significantly higher connection timeout, read/write timeout, and enabling a heartbeat (which shouldn't be used for most connections due to the connection being closed prior to its time being reached).

If I notice a result from this I'll submit a PR.

`
        // create connection with AMQP
        $this->connection = new AMQPStreamConnection(
            $config['host'],
            $config['port'],
            $config['login'],
            $config['password'],
            $config['vhost'],
            false,
            'AMQPLAIN',
            null,
            'en_US',
            120.0,
            180.0,
            null,
            true,
            60
        );
`

**Comment by CmdrSharp** [comment]
Didn't seem to give any immediate result, but I'll let it run for a bit and see if I can detect a long-term difference. Currently modified 180 down to 120 as well, and turned off keepalive.

This was the error according to Rabbit:

=ERROR REPORT==== 22-Aug-2017::07:37:52 ===
closing AMQP connection <0.21978.725> x:43926 -> x:5672):
{handshake_timeout,handshake}

Currently running some connection diagnostics as well to rule out an issue on that end. I'll keep the issue updated with what I can find.

**Comment by CmdrSharp** [comment]
After further troubleshooting, I don't believe the issue to be the connection - nor do I believe it's related to this project. It may be the result of a job not processing somewhere, and thus exceeding the connection timeout. I'll open another issue with further details if I can get to the bottom of it, and if I believe the issue could and should be resolved within the project.

**Comment by CmdrSharp** [comment]
I'll add after some further investigation that it seems to only affect non-daemonized queue workers. My assumption is that either this project, or more likely php-ampqlib, sometimes doesn't properly close the connection - thus rendering this message after some sort of heartbeat timeout. That's just a wild guess however, based on the errors not appearing under any queue that is daemonized.
