### ISSUE TITLE
error when work on laravel 5.5

### ISSUE THREAD

**Issue by terryzwt** [vyuldashev/laravel-queue-rabbitmq#139]
the composer.json snippet
<pre>
    "require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-ide-helper": "^2.4",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "predis/predis": "^1.1",
        "vladimir-yuldashev/laravel-queue-rabbitmq": "5.5"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7",
        "guzzlehttp/guzzle":  "~6.3"
    },
</pre>
here is the error logs:
<pre>
[2017-09-01 09:30:57] local.ERROR: Undefined index: arguments {"exception":"[object] (ErrorException(code: 0): Undefined index: arguments at /app/web/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:47)
[stacktrace]
#0 /app/web/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php(47): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/app/web/vendor...', 47, Array)
#1 /app/web/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Connectors/RabbitMQConnector.php(35): VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue->__construct(Object(PhpAmqpLib\\Connection\\AMQPStreamConnection), Array)
#2 /app/web/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(157): VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Connectors\\RabbitMQConnector->connect(Array)
#3 /app/web/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(138): Illuminate\\Queue\\QueueManager->resolve('rabbitmq')
#4 /app/web/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(104): Illuminate\\Queue\\QueueManager->connection('rabbitmq')
#5 /app/web/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('rabbitmq', 'oc-order', Object(Illuminate\\Queue\\WorkerOptions))
#6 /app/web/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('rabbitmq', 'oc-order')
#7 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#8 /app/web/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /app/web/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /app/web/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /app/web/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /app/web/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\\Container\\Container->call(Array)
#13 /app/web/vendor/symfony/console/Command/Command.php(264): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /app/web/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /app/web/vendor/symfony/console/Application.php(888): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /app/web/vendor/symfony/console/Application.php(224): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /app/web/vendor/symfony/console/Application.php(125): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /app/web/vendor/laravel/framework/src/Illuminate/Console/Application.php(82): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /app/web/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(125): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /app/web/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"}
</pre>

**Comment by vyuldashev** [comment]
Should be fixed now. Can you try again?

**Comment by terryzwt** [comment]
but I don't see any new commit. how you get it fixed?

**Comment by vyuldashev** [comment]
There is commit which references this issue

**Comment by terryzwt** [comment]
it works! thanks for your quick fix!
