### ISSUE TITLE
AMQP interop

### ISSUE THREAD

**Issue by makasim** [vyuldashev/laravel-queue-rabbitmq#153]
Would you be interested to migrate to [amqp interop](https://github.com/queue-interop/queue-interop#amqp-interop). The biggest advantage among others is that it would work with php-amqplib, amqp-ext, and bunny libraries.

I can work on a PR.

**Comment by vyuldashev** [comment]
Currently, this library uses `php-amqplib/php-amqplib`, what we will benefit by migrating to amqp interop library?

**Comment by makasim** [comment]
amqp interop is not a library itself, It is [a set of interfaces](https://github.com/queue-interop/amqp-interop). There are three transports implement them: [enqueue/amqp-ext](https://github.com/php-enqueue/amqp-ext) based on [php amqp extension](https://github.com/pdezwart/php-amqp), [enqueue/amqp-lib](https://github.com/php-enqueue/amqp-lib) based on `php-amqplib/php-amqplib` and [enqueue/amqp-bunny](https://github.com/php-enqueue/amqp-bunny) based on [bunny](https://github.com/jakubkulhan/bunny). 

* `vladimir-yuldashev/laravel-queue-rabbitmq` would rely on interfaces, not on implementation as it is now.
* They share same interfaces
* They are interchangeable 
* Any new implementations will just work. 
* Amqp interop API is cleaner and easier to understand than the API of phpamqp-lib. Compare [phpamqp-lib based](https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/php-amqp/receive_logs_direct.php) tutorials with [interop ones](https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/php-interop/receive_logs_direct.php)

**Comment by makasim** [comment]
I also invited you to join the interop group.
