### ISSUE TITLE
Fails to acknowledge jobs for long time processes

### ISSUE THREAD

**Issue by ahmadhashlamoun** [vyuldashev/laravel-queue-rabbitmq#177]
I'n using laravel v5.0 with version 5.0 of your package, everything is doing well with short time jobs, ones taking less than 3 or 4 mints, but I'm trying to run a queue listener for jobs taking more than 10 mints, the thing is they don't get acknowledged and they remain in the unacked, and after 16.6 mints they moves to the next job and still not acked. could you guys help?
By the way, I'm getting broken pipe or connection sometimes if the process took too long

**Comment by PaddyHu** [comment]
Same issue here on laravel 5.4

**Comment by ahmadhashlamoun** [comment]
@PaddyHu did you solve with something else? other queuing engine or what did you do regarding this?

**Comment by PaddyHu** [comment]
No, now i try to find out what could be the problem.

**Comment by vyuldashev** [comment]
I guess this should help: https://laravel.com/docs/5.4/queues#max-job-attempts-and-timeout

**Comment by PaddyHu** [comment]
No, it's not the worker timeout, i run worker with --timeout=0, and it it would be the worker timeout the jobs would be acked and retried.
I tested a lot and found that the processes finish their job but lost connection with rabbitmq so cant send acknoledgement, and they cant get any other jobs just sitting there and waiting forever. So they lost connection with rabbitmq server.

I think maybe it could be because this package can't read configs to pass keepalive, heartbeat and timeout to the coonnection, and the default heartbeat is 0 so  doesnt send sign to the rabbit server and tcp connection lost.

**Comment by vyuldashev** [comment]
Try setting timeout in your job. 0 won't work, try setting a big integer value. We encountered the same problem, solved by setting timeout in a job.

```php
<?php

namespace App\Jobs;

class ProcessPodcast implements ShouldQueue
{
    /**
     * The number of seconds the job can run before timing out.
     *
     * @var int
     */
    public $timeout = 120;
}
```

**Comment by PaddyHu** [comment]
I tried with big int value also, and unfortunately it doesnt solved the problem. It's a connection with rabbit server cause the job finishes his work.

I get this error too sometimes if the worker waiting a long time after job run:

`In StreamIO.php line 282:
                                                               
  fwrite(): send of 19 bytes failed with errno=32 Broken pipe `

**Comment by ahmadhashlamoun** [comment]
@vyuldashev I'm using Laravel 5.0, and I tried setting the timeout to 0 as well but it didn't solve it, and my job sometimes taking something like 20 mints. What @PaddyHu  said above is totally true, the problem is losing connection with rabbitmq server, but the job I'm pretty sure it finishes.

**Comment by ahmadhashlamoun** [comment]
@vyuldashev any updates here?

**Comment by PaddyHu** [comment]
We found out what was the problem at our company. The TCP connection was interrupted by LVS load balancer. So it's not the projects problem, sorry!
