### ISSUE TITLE
Queue Not Processing

### ISSUE THREAD

**Issue by harshgaur** [vyuldashev/laravel-queue-rabbitmq#179]
Hi There,

First of all thanks for the package for RabbitMQ. I am able to push the queue to Rabbit MQ host but when I try to execute the queue with php artisan queue:work command the queue does not work it is there in the queue but not getting executed.

**Comment by nashlibby** [comment]
me too

**Comment by adam-boduch** [comment]
Me too.

**Comment by nashlibby** [comment]
thanks, only default can run now!

**Comment by vyuldashev** [comment]
You can define connection and many other options. Just go through:

```
php artisan help queue:work
```
