### ISSUE TITLE
我使用你的扩展会很慢

### ISSUE THREAD

**Issue by flc1125** [vyuldashev/laravel-queue-rabbitmq#181]
- laravel: 5.5.27
- vladimir-yuldashev/laravel-queue-rabbitmq: 6.0.3

使用这个扩展很慢，queue(`incoming`)的速度从没有超过30/s

----------------

**但是：**

- laravel: 5.5.27
- vladimir-yuldashev/laravel-queue-rabbitmq: 5.5

使用这个版本就很快。但这个版本的`$this->release()`会有bug

> 请问是哪里配置的问题

**Comment by macoto-liu** [comment]
thought you should type english here, otherwise no one will care about you.
