### ISSUE TITLE
No connector for [] on remote connections

### ISSUE THREAD

**Issue by SamAriafar** [vyuldashev/laravel-queue-rabbitmq#183]
I'm experiencing an exception after switching to a remote RabbitMQ server while on local environment it was working fine.

> ERROR: InvalidArgumentException: No connector for [] in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:172
> Stack trace:
> #0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(156): Illuminate\Queue\QueueManager->getConnector(NULL)
> #1 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(138): Illuminate\Queue\QueueManager->resolve('rabbitmq')
> #2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(104): Illuminate\Queue\QueueManager->connection('rabbitmq')
> #3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('rabbitmq', 'default', Object(Illuminate\Queue\WorkerOptions))
> #4 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('rabbitmq', 'default')
> ...

Both Laravel & laravel-queue-rabbitmq package which I'm using are at v5.4

**Comment by linyanzhou** [comment]
how to fix it ?  A same Error happend to me
