### ISSUE TITLE
New config will not work properly with Laravel ListenCommand/WorkCommand

### ISSUE THREAD

**Issue by altaraven** [vyuldashev/laravel-queue-rabbitmq#187]
**vladimir-yuldashev/laravel-queue-rabbitmq v7.0.2**
**laravel/framework v5.6.22**

See:
\Illuminate\Queue\Console\ListenCommand::getQueue
\Illuminate\Queue\Console\WorkCommand::getQueue

        return $this->input->getOption('queue') ?: $this->laravel['config']->get(
            "queue.connections.{$connection}.queue", 'default'
        );

These Commands expects queue name to be in this place of config, not ...options.queue.name. They can't retrieve it from new version config.
So, the Queue will work ONLY if you specify the queue name:

`php artisan queue:work --queue=queue_name`

In previous versions of package (e.g. 5.5) the package config was compatible with laravel's one and command just took the queue name from config.
Of course, I can add old option to the `api/config/queue.php` and it will work, but this is a shit code approach, right? Maybe overriden commands innjection will be a good way if you are so willing to have new config structure at `vendor/vladimir-yuldashev/laravel-queue-rabbitmq/config/rabbitmq.php`?

**Comment by vyuldashev** [comment]
You are right, current config seems to be wrong, but we cannot make such changes in current version.

We can remain as it is for now and wait till 5.7 arrives or change config and tag a major version (8.0).

**Comment by altaraven** [comment]
You mean Laravel 5.7 queue.php will have the same structure as yours? How do you know that?

**Comment by vyuldashev** [comment]
No, I mean we can make these changes in 5.7 if it does not hurt for now. You are the only one who notices this, by the way :) In my applications I specify queue name in workers always. I guess the others do the same.

**Comment by altaraven** [comment]
Well, the project's queue stopped working after package update. I used basic config from package, didn't override anything in project config. Thats why I've noticed. 

There are no instructions to override laravel's config in your docs, only .env setup. Thats why I didnt do it

**Comment by vyuldashev** [comment]
I just committed changes that resolve this issue. You can view them above in commit  9764821

As for version 7 `options.queue.name` will remain, but package will prefer to use `queue` value. 

Can you install `7.0@dev` and confirm that now it works as expected?

**Comment by vyuldashev** [comment]
@altaraven ?

**Comment by altaraven** [comment]
sorry, can't test it for now, maybe later

**Comment by vyuldashev** [comment]
@altaraven ?

**Comment by altaraven** [comment]
@vyuldashev looks llike the problem is resolved (tried 7.1.1)
