### ISSUE TITLE
Rabbitmq lazy connector. 

### ISSUE THREAD

**Issue by ed-fruty** [vyuldashev/laravel-queue-rabbitmq#190]
Please review my [PR #188 ](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/188).
It allows to configure `RabbitMQ connector` only when `queue` is resolved, no force queue manager initialization more.

**Comment by vyuldashev** [comment]
Hello, @ed-fruty 

I think publishing `rabbitmq.php` is a good idea. Adding a connection configuration to `queue.php` is the only way to use this package.
