### ISSUE TITLE
No connector for [rabbitmq]

### ISSUE THREAD

**Issue by D-Skywalker** [vyuldashev/laravel-queue-rabbitmq#194]
Hi, I am having this exception message(No connector for [rabbitmq]) when I try dispatch a Job on my Rabbit Queue. Yesterday it was running normally, but I did something that broke the code. I found other issues like this here, but very old, so the solutions don't correspond to my code anymore.

Do you have some clue about how to identify what happen? I tried debbug of code, but without success, the exception is throwed in a very deep part of code, so is very complex to someone who has not experience, like me.

**Comment by vyuldashev** [comment]
Hello, I guess you didn't install package and/or did not declare service provider in `config/app.php` if your Laravel is below 5.5.
