### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by soorya54** [vyuldashev/laravel-queue-rabbitmq#195]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vladimir-yuldashev/laravel-queue-rabbitmq 5.2@dev -> satisfiable by vladimir-yuldashev/laravel-queue-rabbitmq[5.2].
    - Conclusion: remove laravel/framework v5.4.36
    - vladimir-yuldashev/laravel-queue-rabbitmq 5.2 requires illuminate/queue 5.2.* -> satisfiable by illuminate/queue[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/queue v5.2.0|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.19|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.21|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.24|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.25|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.26|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.27|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.28|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.31|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.32|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.37|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.43|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.45|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.6|don't install laravel/framework v5.4.36
    - don't install illuminate/queue v5.2.7|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework 5.4.36 -> satisfiable by laravel/framework[v5.4.36].

**Comment by lifamomo** [comment]
I also met the same problem.

**Comment by lifamomo** [comment]
You can try this and specify the laravel version after the command:

     composer require vladimir-yuldashev/laravel-queue-rabbitmq:5.4
