### ISSUE TITLE
handle method isn't triggered 

### ISSUE THREAD

**Issue by jasonrgd** [vyuldashev/laravel-queue-rabbitmq#203]
I can see a serialised object created in rabbitmq . However the worker doesn't pick that job up and process it. I have run php artisan queue:listen but no job get's processed. Yes QUEUE_CONNECTION=rabbitmq has been set. I'm using Laravel 5.7

To see if I was doing something wrong. I switched QUEUE_CONNECTION=database and tried my code again. This time it would pass. I could see the database queue would pick up my job and process it.

**Comment by jasonrgd** [comment]
I have tracked down the issue to be vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:138 $consumer = $this->context->createConsumer($queue);

**Comment by blac3kman** [comment]
> I have tracked down the issue to be vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:138 $consumer = $this->context->createConsumer($queue);

So...Maybe my experience will help you. 
If you use 'the dispatch' method in your laravel project for pushing data into a queue then
your job's code will work out of the box I mean the 'handle' method in job

 ```php
    //for producing    
    SomeJobName::dispatch($payload)->onQueue('some.queue.name');
      
      
    //for consumering
    class SomeJobName implements ShouldQueue
    {
        use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
         
        public function __construct($payload)
        {
             //code
        }

    
        public function handle()
        {
          //code
        }
    }   
```

Another situation:

```php
    ///for producing 
    Queue::push(
        'App\Jobs\JobClassName',
        $payload
        'queue.name'
    );

     //for consumering
    class JobClassName
    {
        use InteractsWithQueue, Queueable, SerializesModels;
         
       //without a constructor!!!!

    
       public function fire($job, $data)
       {
          //code
          $job->delete();
       }
    }
```

It dependes how you are pushing data into a quque. So I decided when I use 'dispatch'  my Jobs' code lives in 'namespace App\Jobs;' And if I use a facace Queue:push, my Jobs' codes in 'namespace App\Tasks;'. I separate them but use the same driver the rabbimq.
