### ISSUE TITLE
Is there any example how to use it for microservices architecture. 

### ISSUE THREAD

**Issue by nadeemse** [vyuldashev/laravel-queue-rabbitmq#213]
Is there any example code on how to handle services to service communication. Let say user register on an ACCOUNT service and now we have you send an email from Deliverability service. so how can we achieve this kind of scenario.

**Comment by vyuldashev** [comment]
You can use ```Queue::push``` and define your own payload structure.

**Comment by priya1890** [comment]
The Queue::push also works only in the same service where it has been pushed. How to consume the message in another service
