### ISSUE TITLE
AMQP error while attempting pop: fwrite(): send of 79 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by joinive** [vyuldashev/laravel-queue-rabbitmq#215]
AMQP error while attempting pop: fwrite(): send of 79 bytes failed with errno=32 Broken pipe

**Comment by Somethingideally** [comment]
Same issue. Any ideas?

**Comment by makasim** [comment]
One of the possible cases: A job execution takes more time than a connection timeout.

**Comment by vyuldashev** [comment]
We are not experiencing such issues. Check your RabbitMQ installation and worker configuration.
