### ISSUE TITLE
AMQP error while attempting pushRaw: Broken pipe or closed connection.

### ISSUE THREAD

**Issue by crcms** [vyuldashev/laravel-queue-rabbitmq#220]
After testing, in the case of using swoole, the queue is not destroyed. If the queue is not executed frequently, the following error will occur in the time-out queue:
```
AMQP error while attempting pushRaw: Broken pipe or closed connection.
```
Partial trace information：
```
"file" : "/var/www/vendor/bunny/bunny/src/Bunny/AbstractClient.php:306",
"trace" : [ 
    "/var/www/vendor/bunny/bunny/src/Bunny/Client.php:87", 
    "/var/www/vendor/bunny/bunny/src/Bunny/ClientMethods.php:1311", 
    "/var/www/vendor/bunny/bunny/src/Bunny/ChannelMethods.php:127", 
    "/var/www/vendor/enqueue/amqp-bunny/AmqpContext.php:278", 
    "/var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:231", 
    "/var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:72", 
    "/var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:61", 
    "/var/www/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:44", 
    "/var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:177", 
    "/var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:160", 
    "/var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:73", 
]
```

Found because of the heartbeat problem, there is a fix in the [0.9 version](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/transport/amqp_lib.md#long-running-task-and-heartbeat-and-timeouts)

[https://github.com/php-enqueue/enqueue-dev/issues/461](https://github.com/php-enqueue/enqueue-dev/issues/461)

Can you consider upgrading the amqp-bunny package to 0.9?

Thank you very much

**Comment by vyuldashev** [comment]
Updated to 0.9. Can you confirm it is fixed now?

**Comment by crcms** [comment]
I am not too sure, I will try to optimize my swoole code first, and other ways to debug,
But I still hope that you can upgrade to the latest 0.9 version.
Please close this question for the time being, thank you

**Comment by namerci** [comment]
I have the same problem.

In my case, I use docker-compose for whole app. I run one instance of RabbitMQ and 30 instances of workers with docker-compose up -d --scale worker=30

After some time, workers lost connection randomly and never reconnect to RabbitMQ. Expected behaviour would be they can try to simply re-connect.

**Comment by xunaiwei** [comment]
这个怎么解决呢
