### ISSUE TITLE
RabbitMQ Jobs are missing from the "Failed Job" Section in Horizon.

### ISSUE THREAD

**Issue by adm-bome** [vyuldashev/laravel-queue-rabbitmq#230]
I've played for some time with horizon sinds you released the new capability for Horizon Support.

If I understand correctly the environment variable `QUEUE_DRIVER` **must** be assigned the value `redis`. (as stated in  the documentation of Horizon)

When i was testing, my driver was by default `rabbitmq`. But i couldn't get the failed_jobs working in Horizon.
When i was dispaching jobs, the jobs would be handled by horizon and when the jobs failed they wouldn't turn-up in the "Failed Job" section of horizon. Although they were marked as `failed` in the section "Recent Jobs" section.

When I changed the default `QUEUE_DRIVER` to `redis` horizon worked as it should, but only when Jobs are dispatched over the connection `redis`.

When I create Jobs and want to use RabbitMQ as broker, I have to assign/set the connection/driver to `rabbitmq` for this created Job like so:

```php
class ProcessUser implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    private $user;

    /**
     * Create a new job instance.
     *
     * @param User $user
     */
    public function __construct(User $user)
    {

        $this->onQueue(kebab_case(class_basename(self::class)));
        $this->onConnection('rabbitmq');

        # Assign User model
        $this->user = $user;
    }
}
```

> You can still override the connection/queue when dispatching the Job.

But when processing these rabbit jobs through horizon workers, the same behavior occurred. No failed_jobs in the "Failed Job" section.

Did you get this to work? What am i doing wrong? Am i missing something?

_Originally posted by @adm-bome in https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/225#issuecomment-472192448_

**Comment by adm-bome** [comment]
After digging into the code of Horizon I came across the events Horizon listens to.

In Horizon the event `\Illuminate\Queue\Events\JobFailed` is registered with a listner `vendor/laravel/horizon/src/Listeners/MarshalFailedEvent`.
This listener won't dispatch a `Laravel\Horizon\Events\JobFailed` event, if the job is not a instance of `Illuminate\Queue\Jobs\RedisJob`.

The solution:

In this package register an new listener on the event `\Illuminate\Queue\Events\JobFailed`.
This listener should dispatch a `Laravel\Horizon\Events\JobFailed` event.

I got it working with the following code:

```php
namespace Laravel\Horizon\Listeners;

use Illuminate\Queue\Jobs\RedisJob;
use Illuminate\Support\Facades\Log;
use Laravel\Horizon\Events\JobFailed;
use Illuminate\Contracts\Events\Dispatcher;
use Illuminate\Queue\Events\JobFailed as LaravelJobFailed;
use VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob;

class MarshalFailedEvent
{
    /**
     * The event dispatcher implementation.
     *
     * @var \Illuminate\Contracts\Events\Dispatcher
     */
    public $events;

    /**
     * Create a new listener instance.
     *
     * @param  \Illuminate\Contracts\Events\Dispatcher  $events
     * @return void
     */
    public function __construct(Dispatcher $events)
    {
        $this->events = $events;
    }

    /**
     * Handle the event.
     *
     * @param  \Illuminate\Queue\Events\JobFailed  $event
     * @return void
     */
    public function handle(LaravelJobFailed $event)
    {
        if ($event->job instanceof RedisJob) {
            $this->events->dispatch((new JobFailed(
                $event->exception, $event->job, $event->job->getReservedJob()
            ))->connection($event->connectionName)->queue($event->job->getQueue()));
        }

        if ($event->job instanceof RabbitMQJob) {
            $this->events->dispatch((new JobFailed(
                $event->exception, $event->job, $event->job->getRawBody()
            ))->connection($event->connectionName)->queue($event->job->getQueue()));
        }

    }
}
```

> Note the 3rd parameter of JobFailed class. because the ReservedJob method does not exist on a RabbitMQJob.

In this snipped i did not separate the event dispatching into 2 classes. (this was only for testing purpose). 
The code should be placed in a seperated class  `VladimirYuldashev\LaravelQueueRabbitMQ\Listeners\RabbitMQHorizonFailedEvent`, or so.

Of course the listener must be only registered when Horizon is detected or the option `worker`  is set `horizon`.

@vladkucherov what do you think of this solution?

**Comment by vyuldashev** [comment]
I will investigate and fix it by the end of the week.

**Comment by vyuldashev** [comment]
v7.4.1 releases. Big thanks @adm-bome for fixing this!
