### ISSUE TITLE
Failed to install package in Centos 7

### ISSUE THREAD

**Issue by teddyhendryanto** [vyuldashev/laravel-queue-rabbitmq#237]
Hi @vyuldashev .
I can't install this package in centos.
It always returns:
**composer install**
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-amqplib/php-amqplib v2.9.1 -> satisfiable by php-amqplib/php-amqplib[v2.9.1].
    - php-amqplib/php-amqplib v2.9.1 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
  Problem 2
    - php-amqplib/php-amqplib v2.9.1 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - enqueue/amqp-lib 0.9.8 requires php-amqplib/php-amqplib ^2.8 -> satisfiable by php-amqplib/php-amqplib[v2.9.1].
    - Installation request for enqueue/amqp-lib 0.9.8 -> satisfiable by enqueue/amqp-lib[0.9.8].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
    - /etc/php.d/10-opcache.ini
    - /etc/php.d/15-xdebug.ini
    - /etc/php.d/20-bz2.ini
    - /etc/php.d/20-calendar.ini
    - /etc/php.d/20-ctype.ini
    - /etc/php.d/20-curl.ini
    - /etc/php.d/20-dom.ini
    - /etc/php.d/20-exif.ini
    - /etc/php.d/20-fileinfo.ini
    - /etc/php.d/20-ftp.ini
    - /etc/php.d/20-gd.ini
    - /etc/php.d/20-gettext.ini
    - /etc/php.d/20-iconv.ini
    - /etc/php.d/20-imap.ini
    - /etc/php.d/20-intl.ini
    - /etc/php.d/20-json.ini
    - /etc/php.d/20-ldap.ini
    - /etc/php.d/20-mbstring.ini
    - /etc/php.d/20-mysqlnd.ini
    - /etc/php.d/20-pdo.ini
    - /etc/php.d/20-pgsql.ini
    - /etc/php.d/20-phar.ini
    - /etc/php.d/20-posix.ini
    - /etc/php.d/20-pspell.ini
    - /etc/php.d/20-recode.ini
    - /etc/php.d/20-shmop.ini
    - /etc/php.d/20-simplexml.ini
    - /etc/php.d/20-soap.ini
    - /etc/php.d/20-sockets.ini
    - /etc/php.d/20-sqlite3.ini
    - /etc/php.d/20-sysvmsg.ini
    - /etc/php.d/20-sysvsem.ini
    - /etc/php.d/20-sysvshm.ini
    - /etc/php.d/20-tidy.ini
    - /etc/php.d/20-tokenizer.ini
    - /etc/php.d/20-xml.ini
    - /etc/php.d/20-xmlwriter.ini
    - /etc/php.d/20-xsl.ini
    - /etc/php.d/30-mcrypt.ini
    - /etc/php.d/30-mysqli.ini
    - /etc/php.d/30-pdo_mysql.ini
    - /etc/php.d/30-pdo_pgsql.ini
    - /etc/php.d/30-pdo_sqlite.ini
    - /etc/php.d/30-wddx.ini
    - /etc/php.d/30-xmlreader.ini
    - /etc/php.d/40-apcu.ini
    - /etc/php.d/40-igbinary.ini
    - /etc/php.d/40-memcache.ini
    - /etc/php.d/40-msgpack.ini
    - /etc/php.d/40-zip.ini
    - /etc/php.d/50-memcached.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

I tried to install php-bcmath using **sudo yum install php-bcmath**, 
and it returns

**sudo yum install yum install php-bcmath**
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
 * base: centos.usonyx.net
 * epel: sg.fedora.ipserverone.com
 * extras: centos.usonyx.net
 * remi-safe: mirror.xeonbd.com
 * updates: centos.usonyx.net
 * webtatic: uk.repo.webtatic.com
No package install available.
Resolving Dependencies
--> Running transaction check
---> Package php-bcmath.x86_64 0:5.4.16-46.el7 will be installed
--> Processing Dependency: php-common(x86-64) = 5.4.16-46.el7 for package: php-bcmath-5.4.16-46.el7.x86_64
---> Package yum.noarch 0:3.4.3-158.el7.centos will be updated
---> Package yum.noarch 0:3.4.3-161.el7.centos will be an update
--> Finished Dependency Resolution
Error: Package: php-bcmath-5.4.16-46.el7.x86_64 (base)
           Requires: php-common(x86-64) = 5.4.16-46.el7
           Installed: php-common-7.2.13-2.el7.remi.x86_64 (@remi-php72)
               php-common(x86-64) = 7.2.13-2.el7.remi
           Available: php-common-5.4.16-46.el7.x86_64 (base)
               php-common(x86-64) = 5.4.16-46.el7
           Available: php55w-common-5.5.38-1.w7.x86_64 (webtatic)
               php-common(x86-64) = 5.5.38-1.w7
           Available: php56w-common-5.6.40-1.w7.x86_64 (webtatic)
               php-common(x86-64) = 5.6.40-1.w7
           Available: php70w-common-7.0.33-1.w7.x86_64 (webtatic)
               php-common(x86-64) = 7.0.33-1.w7
           Available: php71w-common-7.1.26-1.w7.x86_64 (webtatic)
               php-common(x86-64) = 7.1.26-1.w7
           Available: php71w-common-7.1.27-1.w7.x86_64 (webtatic)
               php-common(x86-64) = 7.1.27-1.w7
           Available: php72w-common-7.2.14-1.w7.x86_64 (webtatic)
               php-common(x86-64) = 7.2.14-1.w7
           Available: php72w-common-7.2.16-1.w7.x86_64 (webtatic)
               php-common(x86-64) = 7.2.16-1.w7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

I tried to install php-common using sudo yum install php-common 
It always returns

sudo yum install php-common
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
 * base: centos.usonyx.net
 * epel: sg.fedora.ipserverone.com
 * extras: centos.usonyx.net
 * remi-safe: mirror.xeonbd.com
 * updates: centos.usonyx.net
 * webtatic: uk.repo.webtatic.com
rabbitmq_erlang/x86_64/signature                                                                                                                                                                                      |  833 B  00:00:00
rabbitmq_erlang/x86_64/signature                                                                                                                                                                                      | 1.0 kB  00:00:00 !!!
rabbitmq_erlang-source/signature                                                                                                                                                                                      |  819 B  00:00:00
rabbitmq_erlang-source/signature                                                                                                                                                                                      |  951 B  00:00:00 !!!
rabbitmq_rabbitmq-server/x86_64/signature                                                                                                                                                                             |  833 B  00:00:00
rabbitmq_rabbitmq-server/x86_64/signature                                                                                                                                                                             | 1.0 kB  00:00:00 !!!
rabbitmq_rabbitmq-server-source/signature                                                                                                                                                                             |  836 B  00:00:00
rabbitmq_rabbitmq-server-source/signature                                                                                                                                                                             | 1.0 kB  00:00:00 !!!
Package matching php-common-5.4.16-46.el7.x86_64 already installed. Checking for update.
Nothing to do

What should I do?
Please help me.

**Comment by adm-bome** [comment]
Depending on the php version you installed locally. Try to install the correct bcmath.
I guess you have php7.2 installed. with your command you are trying to install bcmath for php5.4.

Try

```bash
sudo apt install php7.2-bcmath
```
or with yum

```bash
yum install php72-php-bcmath
```

**Comment by teddyhendryanto** [comment]
Thank you for you help.
yum install php72-php-bcmath works.
