### ISSUE TITLE
Call to undefined method VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue::readyNow()

### ISSUE THREAD

**Issue by AuditeMarlow** [vyuldashev/laravel-queue-rabbitmq#239]
I've updated my composer packages last week, and Horizon no longer seems to be able to pick up jobs. Upon opening the Horizon dashboard, I receive this error in one of the asynchronous calls that is fired by Horizon.

This results in the Horizon dashboard counters staying still at 0 each. The started queue workers are displayed however. Horizon's "Recent Jobs" and "Failed Jobs" are completely empty too.

I'm running Laravel 5.7.28, Horizon 3.1.1 and this library at 7.5.0. I'm not very familiar with how queuing works behind the scenes and what might've changed in Horizon.

**Comment by vyuldashev** [comment]
Horizon is supported from 8.0, we reverted changes in 7.5.0 due to backward incompatible changes.

**Comment by AuditeMarlow** [comment]
I've upgraded RabbitMQ driver library to 8.0 and everything seems to be working fine again. Thanks!

**Comment by amirhosseindz** [comment]
Same here.. I'm using version 8.2 of this package.
