### ISSUE TITLE
Error 'Error writing data to the connection with RabbitMQ'

### ISSUE THREAD

**Issue by JiaHangSama** [vyuldashev/laravel-queue-rabbitmq#249]
I set RABBITMQ_ERROR_SLEEP=false,occasionally an error ‘Error writing data to the connection with RabbitMQ’ when pushing a message.
If I don't set it, the message will not be pushed successfully.
What is the problem with this?

**Comment by huzhangzheng** [comment]
what do you do with this issue? Do you fix it yet?
