### ISSUE TITLE
Using library for cross service messaging

### ISSUE THREAD

**Issue by rw4lll** [vyuldashev/laravel-queue-rabbitmq#252]
Hello, Vladimir! We are using rabbitmq as common bus to listen and emitting events between different services. So, we have different data structure of queue and laravel cannot find specific event class there. How can I listen all non-laravel events in specific queue and handle it manually?

**Comment by hex7c0** [comment]
hey @rw4lll 
we're using this PR https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/247 to use a different data structure, if can help ;)

**Comment by rw4lll** [comment]
@hex7c0 thank you! :)
