### ISSUE TITLE
Argument 1 passed to Interop\Amqp\Impl\AmqpTopic::setArguments()

### ISSUE THREAD

**Issue by nanophp** [vyuldashev/laravel-queue-rabbitmq#253]
**Hi Laravel version: 5.8.26
Library version : 8.2.0
PHP version: 7.2.4**

Argument 1 passed to Interop\Amqp\Impl\AmqpTopic::setArguments() must be of the type array, null given, called in /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php on line 216

code location:

```
79     public function setArguments(array $arguments): void

80     {

81         $this->arguments = $arguments;

82     }

```
stack trace

```

/var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:216
--

```

**Comment by nanophp** [comment]
@vyuldashev please, I need fix this issue

**Comment by vyuldashev** [comment]
Whats  your config and what causes this error to happen?
