### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by 1210mk2** [vyuldashev/laravel-queue-rabbitmq#254]
Hello.
The array we see on mainpage works fine for PHP7.
I could not use it for PHP5.4 and laravel 5.
things like 
`'factory_class' => Enqueue\AmqpLib\AmqpConnectionFactory::class,`
are impossible.
Can you add a notice that old version PHP users
should use an array from examples?
Thanks.

**Comment by vyuldashev** [comment]
Minimal PHP version matches Laravel's minimal ones. ^7.1.3

**Comment by 1210mk2** [comment]
thanks for reply. Laravel 5.0 allows PHP 5.4, I have an application working that way.
I've changed settings array to the style found in examples,
then I had to add a string to ServiceProviders
'VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider'
(would be nice to see it mentioned in Installation manual also)
and finally it works fine.
