### ISSUE TITLE
Upgrading to higher version

### ISSUE THREAD

**Issue by ilyachase** [vyuldashev/laravel-queue-rabbitmq#255]
Hi there.
It seems that maintainer started using semver. Is there any kind of changelog? Major version is often changes, but I have no idea what was broken in every version.

**Comment by vyuldashev** [comment]
@ilyachase I will take some time to add version compatibility table and add changelog. If anyone wants to help I will appreciate it.

**Comment by ilyachase** [comment]
@vyuldashev so you just closed the issue? :)
