### ISSUE TITLE
'routing_key' - How to implement it?

### ISSUE THREAD

**Issue by vlauciani** [vyuldashev/laravel-queue-rabbitmq#256]
Hi

I'm using this package to send message on a RabbitMQ server; I'd like to use `routing_key` and looking the comment:
- https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/98#issuecomment-512693558

I tried to add `routing_key` => `my_key` option, but It doesn't work (for me); sending a message on a `foo` queue, the routing_key is set automatically to `foo`. Example on Laravel:
```
MyJob::dispatch($data)->onConnection('rabbitmq')->onQueue('foo');
``` 

Looking the code, the method `pushRaw()` (https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/master/src/Queue/RabbitMQQueue.php#L66):
```
public function pushRaw($payload, $queueName = null, array $options = []) {
   . . .
}
```

get as third params  `$options = []`. This method ( `pushRaw()` ) is called from: (https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/master/src/Queue/RabbitMQQueue.php#L60):
```
    public function push($job, $data = '', $queue = null)
    {
        return $this->pushRaw($this->createPayload($job, $queue, $data), $queue, []);
    }
```

where the third params is an empty array `[]`.

Is this correct? Where the `$options` array i set?

**Comment by vyuldashev** [comment]
You should probably use `Queue::pushRaw`.
