### ISSUE TITLE
persistent and non-persistent queues/messages

### ISSUE THREAD

**Issue by tayyabhussain** [vyuldashev/laravel-queue-rabbitmq#263]
We are using laravel-queue-rabbitmq 5.1 with laravel 5.1
We want to have some queues persistent and some non-persistent ?
As we have global configuration in config/queue.php
`
'queue_params' => [
                'durable' => env('RABBITMQ_QUEUE_DURABLE', true)
            ],
`
also
`
'exchange_params' => [
                'durable' => env('RABBITMQ_EXCHANGE_DURABLE', true)
            ],
`
which will be the configuration for all the queues,
Question 1 : Is there any way to have different durability for different queues ?
Question 2 : is there any way to change the durability of message ?

@vyuldashev

**Comment by adm-bome** [comment]
Update your laravel :)
The latest version of this lib is recommended.

Question 1 : Is there any way to have different durability for different queues ?
Answer: Yes, but this is only possible when you predeclare queues in rabbitMQ or run the command `php artisan rabbitmq:queue-declare --durable=0 test-queue`

Question 2 : is there any way to change the durability of message ?
Answer: No

>With version 4 or above this library, you can always setup multiple queue connections with different options. And in your Job(s) specify the connection to use.

```
Closing this issue because one of the following:
- No support or fixes for deprecated versions. (Please update your dependencies)
- This is no forum ;)
```
