### ISSUE TITLE
Хотелось бы динамически формировать название очереди

### ISSUE THREAD

**Issue by masterjus** [vyuldashev/laravel-queue-rabbitmq#265]
Hi there
I'm the author of the package https://github.com/nuwber/rabbitevents.
I've got troubles with the previous package, which I've been using to connect to  RabbitMQ.
I'm almost finished to make this switch and got a problem because a queue name is predefined in the config but I need to make it based on input data. So if I want to use the full functionality of your package (like automatically connect to queue) I can't do it.

Please, if I'm wrong and there's a possible way to make queue dynamically, let me know how.

Thank you

**Comment by vyuldashev** [comment]
Hello, Laravel allows you to customise queue name: https://laravel.com/docs/6.0/queues#customizing-the-queue-and-connection

**Comment by vyuldashev** [comment]
I think it’s better to use phpamqp-lib in your case. The goal of this library is to provide a driver for Queue API.
