### ISSUE TITLE
InvalidArgumentException  : No connector for [rabbitmq]

### ISSUE THREAD

**Issue by jsjunior** [vyuldashev/laravel-queue-rabbitmq#266]
Hello.

Ive followed the read me to install this package in a Laravel 6.0.3 project and, setting up rabbitmq as default connection, this error occurs. I have connection setted in `config/queue.php`, updated composer as sugested (just in case as nothing was outdated), no lucky. Any help?

Thanks in advance.

**Comment by vyuldashev** [comment]
Probably you disabled autodiscovery. This can be only explanation.
