### ISSUE TITLE
Timeout after 10 min

### ISSUE THREAD

**Issue by cansozeri** [vyuldashev/laravel-queue-rabbitmq#268]
Hi,

Our consumer is closing the connection if the process takes more than 10 min. There is no option in your config for heartbeat and connection_timeout etc.

Why didn't you add this options, is there any reason for this and if you want it is very easy to add this conf in your codes.

I think this package needs to provide heartbeat option and connection timeout settings too. 

While I consume message, how can I get the connection instance and send heartbeat manually ? Is there anyway to do this ? 

Have a nice day.

**Comment by vyuldashev** [comment]
Hello. I will take into consideration this issue while developing v10. Will get back to this issue with a solution.

**Comment by SchizoDuckie** [comment]
What's the status on this? 
Last mention of the heartbeat was here, where it was disabled. 
I will do some testing on the stability of longer running jobs without supervisor monitoring it.
https://github.com/vyuldashev/laravel-queue-rabbitmq/compare/v10.0.2...v10.1.0#diff-28f3121af9d7915ed07d75ea38918217

**Comment by vyuldashev** [comment]
@SchizoDuckie I tested long running jobs (5 min) and everything works as expected. Let me know if you encounter any problems.

**Comment by vyuldashev** [comment]
v10.2 should fix this
