### ISSUE TITLE
The Queue::push also works only in the same service where it has been pushed. How to consume the message in another service

### ISSUE THREAD

**Issue by priya1890** [vyuldashev/laravel-queue-rabbitmq#275]
The Queue::push also works only in the same service where it has been pushed. How to consume the message in another service

_Originally posted by @priya1890 in https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/213#issuecomment-542239060_

**Comment by mr-feek** [comment]
try `Queue::pushRaw`

**Comment by vyuldashev** [comment]
As @mr-freek mentioned, use Queue::pushRaw or use phpamqp-lib directly.
