### ISSUE TITLE
RABBITMQ_EXCHANGE_TYPE=TYPE_FANOUT   Inability to consume

### ISSUE THREAD

**Issue by JianyuC** [vyuldashev/laravel-queue-rabbitmq#279]
您好：
当设置RABBITMQ_EXCHANGE_TYPE=TYPE_FANOUT 的时候，
以下命令，无法接收到消息
 php artisan queue:work rabbitmq --queue=service_payment_event

**Comment by vyuldashev** [comment]
Should be possible with v10.2.0
