### ISSUE TITLE
ErrorException: Undefined index: queue

### ISSUE THREAD

**Issue by andrey-helldar** [vyuldashev/laravel-queue-rabbitmq#285]
- Laravel Version: 6.6.1
- Package Version: v9.1.2
- RabbitMQ Version: 3.8.2

**Describe the bug**
When the command "php artisan queue:work" is called, an error occurs: `Undefined index: queue`

**Steps To Reproduce**

1. `composer require vladimir-yuldashev/laravel-queue-rabbitmq`
2. The file [configuration](https://github.com/vyuldashev/laravel-queue-rabbitmq#installation) block has been added to file `config/queue.php`.
3. Added keys to file `.env`:

 > QUEUE_CONNECTION=rabbitmq
 > QUEUE_FAILED_DRIVER=rabbitmq
 > 
 > RABBITMQ_HOST=rabbitmq
 > RABBITMQ_PORT=5672
 > RABBITMQ_USER=default
 > RABBITMQ_PASSWORD=secret
 > RABBITMQ_QUEUE=default

4. Call the `php artisan queue:work` command;
5. See error.

```
$ art queue:work -v

   ErrorException  : Undefined index: queue

  at D:\_domains\example.com\vendor\vladimir-yuldashev\laravel-queue-rabbitmq\src\Queue\RabbitMQQueue.php:39
    35|     {
    36|         $this->context = $context;
    37| 
    38|         $this->queueName = $config['queue'] ?? $config['options']['queue']['name'];
  > 39|         $this->queueOptions = $config['options']['queue'];
    40|         $this->queueOptions['arguments'] = isset($this->queueOptions['arguments']) ?
    41|             json_decode($this->queueOptions['arguments'], true) : [];
    42| 
    43|         $this->exchangeOptions = $config['options']['exchange'];

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: queue", "D:\_domains\example.com\vendor\vladimir-yuldashev\laravel-queue-rabbitmq\src\Queue\RabbitMQQueue.php", [Object(Enqueue\AmqpLib\AmqpContext)])
      D:\_domains\example.com\vendor\vladimir-yuldashev\laravel-queue-rabbitmq\src\Queue\RabbitMQQueue.php:39

  2   VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::__construct(Object(Enqueue\AmqpLib\AmqpContext))
      D:\_domains\example.com\vendor\vladimir-yuldashev\laravel-queue-rabbitmq\src\Queue\Connectors\RabbitMQConnector.php:80

  3   VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Connectors\RabbitMQConnector::connect()
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Queue\QueueManager.php:157

  4   Illuminate\Queue\QueueManager::resolve("rabbitmq")
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Queue\QueueManager.php:138

  5   Illuminate\Queue\QueueManager::connection("rabbitmq")
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Queue\Worker.php:118

  6   Illuminate\Queue\Worker::daemon("rabbitmq", "default", Object(Illuminate\Queue\WorkerOptions))
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php:112

  7   Illuminate\Queue\Console\WorkCommand::runWorker("rabbitmq", "default")
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php:96

  8   Illuminate\Queue\Console\WorkCommand::handle()
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  9   call_user_func_array([])
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  10  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Container\Util.php:34

  11  Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:90

  12  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:34

  13  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Container\Container.php:590

  14  Illuminate\Container\Container::call()
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Console\Command.php:202

  15  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      D:\_domains\example.com\vendor\symfony\console\Command\Command.php:255

  16  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Console\Command.php:189

  17  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      D:\_domains\example.com\vendor\symfony\console\Application.php:1011

  18  Symfony\Component\Console\Application::doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      D:\_domains\example.com\vendor\symfony\console\Application.php:272

  19  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      D:\_domains\example.com\vendor\symfony\console\Application.php:148

  20  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Console\Application.php:90

  21  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      D:\_domains\example.com\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:131

  22  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      D:\_domains\example.com\artisan:37
```

** Additional content**
```php
public function __construct(AmqpContext $context, array $config)
{
  dd($config['options']);
```
And see result:
```
$ art queue:work -v
array:1 [
  "ssl_options" => array:5 [
    "cafile" => null
    "local_cert" => null
    "local_key" => null
    "verify_peer" => true
    "passphrase" => null
  ]
]
```

**Comment by andrey-helldar** [comment]
Adding `queue` block to `options` from article https://laravel-news.com/laravel-rabbitmq-queue-driver helped me.

**Comment by GRotger** [comment]
Hi @andrey-helldar, your comment fixed my afternoon :P !

`       
'rabbitmq' => [
           'driver' => 'rabbitmq',
           'queue' => env('RABBITMQ_QUEUE', 'default'),
           'connection' => PhpAmqpLib\Connection\AMQPLazyConnection::class,

            'host' => env('RABBITMQ_HOST', '127.0.0.1'),
            'port' => env('RABBITMQ_PORT', 5672),
            'login' => env('RABBITMQ_LOGIN', 'guest'),
            'password' => env('RABBITMQ_PASSWORD', 'guest'),
            'vhost' => env('RABBITMQ_VHOST', '/'),
            'queue' => env('RABBITMQ_QUEUE', 'default'),

            'hosts' => [
               [
                   'host' => env('RABBITMQ_HOST', '127.0.0.1'),
                   'port' => env('RABBITMQ_PORT', 5672),
                   'user' => env('RABBITMQ_USER', 'guest'),
                   'password' => env('RABBITMQ_PASSWORD', 'guest'),
                   'vhost' => env('RABBITMQ_VHOST', '/'),
               ],
            ],

           'options' => [
                'exchange' => [

                    'name' => env('RABBITMQ_EXCHANGE_NAME'),

                    /*
                    * Determine if exchange should be created if it does not exist.
                    */

                    'declare' => env('RABBITMQ_EXCHANGE_DECLARE', true),

                    /*
                    * Read more about possible values at https://www.rabbitmq.com/tutorials/amqp-concepts.html
                    */

                    'type' => env('RABBITMQ_EXCHANGE_TYPE', \Interop\Amqp\AmqpTopic::TYPE_DIRECT),
                    'passive' => env('RABBITMQ_EXCHANGE_PASSIVE', false),
                    'durable' => env('RABBITMQ_EXCHANGE_DURABLE', true),
                    'auto_delete' => env('RABBITMQ_EXCHANGE_AUTODELETE', false),
                    'arguments' => env('RABBITMQ_EXCHANGE_ARGUMENTS'),
              ],

               'ssl_options' => [
                   'cafile' => env('RABBITMQ_SSL_CAFILE', null),
                   'local_cert' => env('RABBITMQ_SSL_LOCALCERT', null),
                   'local_key' => env('RABBITMQ_SSL_LOCALKEY', null),
                   'verify_peer' => env('RABBITMQ_SSL_VERIFY_PEER', true),
                   'passphrase' => env('RABBITMQ_SSL_PASSPHRASE', null),
               ],
               'queue' => [
                    /*
                     * Determine if queue should be created if it does not exist.
                     */
                    'declare' => env('RABBITMQ_QUEUE_DECLARE', true),

                    /*
                     * Determine if queue should be binded to the exchange created.
                     */
                    'bind' => env('RABBITMQ_QUEUE_DECLARE_BIND', true),

                    /*
                     * Read more about possible values at https://www.rabbitmq.com/tutorials/amqp-concepts.html
                     */

                    'passive' => env('RABBITMQ_QUEUE_PASSIVE', false),
                    'durable' => env('RABBITMQ_QUEUE_DURABLE', true),
                    'exclusive' => env('RABBITMQ_QUEUE_EXCLUSIVE', false),
                    'auto_delete' => env('RABBITMQ_QUEUE_AUTODELETE', false),
                    'arguments' => env('RABBITMQ_QUEUE_ARGUMENTS'),
                ]
           ],

           /*
            * Set to "horizon" if you wish to use Laravel Horizon.
            */
           'worker' => env('RABBITMQ_WORKER', 'default'),

 ]`

This config worker for me!

**Comment by andrey-helldar** [comment]
@vyuldashev, I guess the configuration from readme.md is for the 10-th version of the package. Correctly? But is it under development?

**Comment by vyuldashev** [comment]
@andrey-helldar Yes. I added documentation links for each version to readme.
