### ISSUE TITLE
Set Options before dispatching the job

### ISSUE THREAD

**Issue by T0miii** [vyuldashev/laravel-queue-rabbitmq#288]
- Laravel Version: 6.4
- Package Version: master
- RabbitMQ Version: 3.7.22

This is more of a question then a bug.
Is there a way to set the Correlation Id and other properties before dispatching the job? I see that in the code there are options for this but i just can figure it out how to set it.

```
            ProcessCreateUser::dispatch(
                    $userData
            )->onQueue(config('config.new_app_user'));

```
Do i have to dispatch the job in a different way?

**Comment by vyuldashev** [comment]
No, it's not supported yet.

**Comment by T0miii** [comment]
okay, thx for the response.
