### ISSUE TITLE
Why using basic_get instead of basic_consume on pop?

### ISSUE THREAD

**Issue by itsursujit** [vyuldashev/laravel-queue-rabbitmq#290]
I'm writing this as query to understand the logic behind why you're not using `basic_consume` as it is more preferred over `basic_get`.

Also How would I implement consumer throttling using `basic_qos` using this package? Currently the command is not being used at all.

I just want to understand the basics.
Please do not close this ticket as it's not issue :).

**Comment by vyuldashev** [comment]
`basic_get` is the only way to make this work with Laravel. See #289. Soon, I will release separate `rabbitmq:command` which uses `basic_consume`.

**Comment by vyuldashev** [comment]
Released v10.1.0 with Artisan's `rabbitmq:consume` command.
