### ISSUE TITLE
RabbitMQ not consuming messages from TOPIC/DIRECT Exchange that were already on Queue/Exchange

### ISSUE THREAD

**Issue by itsursujit** [vyuldashev/laravel-queue-rabbitmq#292]
I tried to follow the code mentioned in

https://www.rabbitmq.com/tutorials/tutorial-five-php.html

If I start the worker first and then send Messages from publisher it works as intended. But worker doesn't consume any messages if worker is restarted (Ctrl + C and running worker again) in the middle of messages being sent from publisher. Though messages exists on the queue.

Or If I publish message to exchange and start worker, the worker is not consuming any messages either.

I've attached video for both issue: https://www.loom.com/share/a0ba2522a20b4eee8eebe926eb97e723

Same thing happened when I tried to use this library.

Am I missing something?

**Comment by vyuldashev** [comment]
I think you should ask phpamqplib maintainers as this question is not related to this library.

**Comment by itsursujit** [comment]
Okay! Thanks... and BTW when I use `rabbitmq:consume` to enable consumer, the consumer is taking around 10-12% of CPU. This usages is too high for empty consumer with no messages to consume...

If I use basic_consume function as consumer... there's less or negligible CPU usages.

Is there any way I could reduce CPU usages?

**Comment by itsursujit** [comment]
@vyuldashev I found issue of high CPU usages because of timeout on 
`$this->channel->wait(null, true, (int) $options->timeout);` in Consumer.php

I removed timeout and CPU usages went to 0.

But whenever there's any Exception in Laravel Job, the Consumer is terminated instead it should send back the Job on Queue.

How could I do that?
