### ISSUE TITLE
Missing instance of Illuminate\Container\Container in the RabbitMQJob class

### ISSUE THREAD

**Issue by mohov** [vyuldashev/laravel-queue-rabbitmq#297]
- Laravel Version: 6.10.1
- Package Version: 10
- RabbitMQ Version: 3.7.8

**Describe the bug**
Instance of `Illuminate\Container\Container` in the `RabbitMQJob` class is missed
so `resolve()` method in the `abstract Job` class is not working

**Steps To Reproduce**
Run queue in the my environment noted above.
**Expected behavior**

**Additional context**
I use composer version of your driver.

**Comment by adm-bome** [comment]
Please update dependencies. Use/Try v10.2.0
