### ISSUE TITLE
Unable to change exchange type when pushing to queue

### ISSUE THREAD

**Issue by chinyoongtat** [vyuldashev/laravel-queue-rabbitmq#302]
Hello,

I have declared an exchange with type = fanout

    php artisan rabbitmq:exchange-declare fanout --type=fanout

I have also specified the exchange in my config\queue.php

             'options' => [
                  'exchange' => [

                      // 'name' => env('RABBITMQ_EXCHANGE_NAME'),
                      'name' => 'fanout',

                      /*
                      * Determine if exchange should be created if it does not exist.
                      */
                      'declare' => env('RABBITMQ_EXCHANGE_DECLARE', true),

                      /*
                      * Read more about possible values at https://www.rabbitmq.com/tutorials/amqp-concepts.html
                      */
                      'type' => env('RABBITMQ_EXCHANGE_TYPE', PhpAmqpLib\Exchange\AMQPExchangeType::FANOUT),
                      'passive' => env('RABBITMQ_EXCHANGE_PASSIVE', false),
                      'durable' => env('RABBITMQ_EXCHANGE_DURABLE', true),
                      'auto_delete' => env('RABBITMQ_EXCHANGE_AUTODELETE', false),
                      'arguments' => env('RABBITMQ_EXCHANGE_ARGUMENTS'),
                  ],
                 'ssl_options' => [
                     'cafile' => env('RABBITMQ_SSL_CAFILE', null),
                     'local_cert' => env('RABBITMQ_SSL_LOCALCERT', null),
                     'local_key' => env('RABBITMQ_SSL_LOCALKEY', null),
                     'verify_peer' => env('RABBITMQ_SSL_VERIFY_PEER', true),
                     'passphrase' => env('RABBITMQ_SSL_PASSPHRASE', null),
                 ],
             ],

However, when i'm trying to push my job, I am hitting this error

PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'fanout' in vhost '/': received 'direct' but current is 'fanout'

Kindly help.

**Comment by adm-bome** [comment]
I see you used the config of an previous version (V9 or lower).

In case you used V10:
This is because it's hardcoded into the current version (V10.1.3). pushRaw can only push on a direct queue, bound to an exchange with type DIRECT.

In case you used an earlier version than V10:
This is probably because in an earlier attempt to publish a message a exchange was created with type DIRECT and still exits on the server. Once a exchange is created you can't alter the config. 
Please check if there is an exchange already in RabbitMQ, and delete it.

**Comment by adm-bome** [comment]
@chinyoongtat 

Please verify your issue is resolved with the latest commits
`composer require vyuldashev/laravel-queue-rabbitmq:dev-master`

**Comment by vyuldashev** [comment]
Should be possible with v10.2.0
