### ISSUE TITLE
Laravel Horizon still needs Redis

### ISSUE THREAD

**Issue by bandgeekndb** [vyuldashev/laravel-queue-rabbitmq#306]
- Laravel Version: 6.0.13
- Package Version: 10.1.13
- RabbitMQ Version: 3.7.12

**Describe the bug**
With this package installed and configured, Laravel Horizon still appears to rely on Redis for the inner workings of Horizon. Jobs go to RabbitMQ as expected once Horizon is running, but without Redis, Horizon is unable to start.

**Steps To Reproduce**

- Install and configure Laravel, Horizon, and the laravel-queue-rabbitmq package.
- Ensure Redis is not installed or the service is stopped.
- Attempt to start Horizon

**Expected behavior**
Horizon will fail to start with a Predis\Connection\ConnectionException as Horizon attempts to start a Redis connection.

**Additional context**
Please let me know if you need any other information, thank you for the assistance!

**Comment by vyuldashev** [comment]
Hello. Yes, Redis is still required in order to Horizon to be fully functional.

**Comment by vanloctech** [comment]
I can remove horizon in this rabbitmq package?
