### ISSUE TITLE
Document Breaking Changes

### ISSUE THREAD

**Issue by mr-feek** [vyuldashev/laravel-queue-rabbitmq#307]
I would like to propose that breaking changes are documented in the changelog moving forward. For example, version 10.0 does not have an upgrade guide, and the changes to `config/rabbitmq.php` are not documented anywhere.

I will try to help do this as I complete the migration myself

**Comment by vyuldashev** [comment]
@mr-feek I would appreciate PR with an upgrade guide.

**Comment by adm-bome** [comment]
Moving away from enqueue was nice :+1: 
Now the library is more inline with Laravel and the Queue API.
I think with V10 we moved forward how it was desiged to work.

In pull request #304 i'll try to bring back some of rabbitmq's features and the previous versions of this Library. Were i do complement the use of exchanges.

- Publishing messages is always against an exchange.
- All queues are by default bound to the amq.direct exchange.
- Consumers aren't aware how the messages ends-up in a queue.
- Consumers only know the queue they are bound to.

**Comment by T0miii** [comment]
How should the propper config/queue.php look like ? Cause since 10.1.3  i am getting a lot of connection errors.

**Comment by vyuldashev** [comment]
https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/master/config/rabbitmq.php

**Comment by T0miii** [comment]
ty

**Comment by adm-bome** [comment]
> How should the proper config/queue.php look like ? Cause since 10.1.3 i am getting a lot of connection errors.

As @vyuldashev mentions.
Without mentioning the exact error in an new issue no one can help.

The workers/consumers do have an issue with closed channels. After a while (or immediately) channels are closed because a channel exception was raised. So your 'LOG' will fill-up with a `Channel closed message`.

This should be solved by the next release. 10.2.0
