### ISSUE TITLE
Can't connect to cloudamqp.com

### ISSUE THREAD

**Issue by xXcoronaXx** [vyuldashev/laravel-queue-rabbitmq#309]
- Laravel Version: 6.14.0
- Package Version: 10.1.3
- RabbitMQ Version: cloudamqp.com 3.7.8 Erlang 21.0.6
- PHP 7.2

**Describe the bug**
I can use this plugin with a local container of RabbitMQ (docker), but if i try it with cloudamqp.com i'm not able to connect to the server in the cloud. I always get the error:

"The connection timed out after 3 sec while awaiting incoming data..."

**Steps To Reproduce**
Just install the package and try the free server that they give.

i'm using this conf template, without horizon:
```
        'rabbitmq' => [
    
            'driver' => 'rabbitmq',
            'queue' => env('RABBITMQ_QUEUE', 'default'),
            'connection' => PhpAmqpLib\Connection\AMQPLazyConnection::class,
        
            'hosts' => [
                [
                    'host' => env('RABBITMQ_HOST', '127.0.0.1'),
                    'port' => env('RABBITMQ_PORT', 5672),
                    'user' => env('RABBITMQ_USER', 'guest'),
                    'password' => env('RABBITMQ_PASSWORD', 'guest'),
                    'vhost' => env('RABBITMQ_VHOST', '/'),
                ],
            ],
        
            'options' => [
                'ssl_options' => [
                    'cafile' => env('RABBITMQ_SSL_CAFILE', null),
                    'local_cert' => env('RABBITMQ_SSL_LOCALCERT', null),
                    'local_key' => env('RABBITMQ_SSL_LOCALKEY', null),
                    'verify_peer' => env('RABBITMQ_SSL_VERIFY_PEER', true),
                    'passphrase' => env('RABBITMQ_SSL_PASSPHRASE', null),
                ],
            ],
        
            /*
             * Set to "horizon" if you wish to use Laravel Horizon.
             */
            'worker' => env('RABBITMQ_WORKER', 'default'),
        ],
```

I don't know if i'm missing something to connect to this provider.

Thanks

**Comment by adm-bome** [comment]
@xXcoronaXx 

If you did solve this issue, can you please please provide some more infomation.

Is this still an issue with the latest version?

**Comment by aluisiora** [comment]
@xXcoronaXx Does it work with [amqproxy](https://github.com/cloudamqp/amqproxy)?

**Comment by Christophvh** [comment]
Has anyone solved this? I have the same issue

**Comment by M-Porter** [comment]
Closed due to inactivity.
