### ISSUE TITLE
[Feature] Work with multiple queue on rabbitmq:consumer command

### ISSUE THREAD

**Issue by itsursujit** [vyuldashev/laravel-queue-rabbitmq#318]
- Lumen Version:6.3
- Package Version: latest

When running `php artisan rabbitmq:command --queue="abc,default,xyz"` I'm getting following error

```
In AMQPChannel.php line 215:
                                                                               
  NOT_FOUND - no queue 'store-to-db-queue,store-to-db-prio-3,store-to-db-prio  
  -2,store-to-db-prio-1,store-to-db-prio-0' in vhost '/'  
```
As a possible solution I tried to do following:

```
    $queueName = explode(',', $queue);
        foreach ($queueName as $name) {
            $name = $this->mode . $name;
            $this->channel->queue_declare(
                $name,
                false,
                true,
                false,
                false,
                false
            );
            $this->channel->basic_consume(
                $name,
                '',
                false,
                false,
                false,
                false,
                function (AMQPMessage $message) use ($connection, $options, $connectionName, $name): void {
                    $this->gotJob = true;

                    $job = new RabbitMQJob(
                        $this->container,
                        $connection,
                        $message,
                        $connectionName,
                        $name
                    );

                    if ($this->supportsAsyncSignals()) {
                        $this->registerTimeoutHandler($job, $options);
                    }

                    $this->runJob($job, $connectionName, $options);
                }
            );
        }
```
With above change, jobs are working but when trying to Release a job or retry a job or delay a job,
I'm getting following error:

`PRECONDITION_FAILED - unknown delivery tag 3`

How to fix such issue?

**Comment by adm-bome** [comment]
Try the master until the new code is released.
See also my [comment](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/303/files#r375932387)

`composer require vyuldashev/laravel-queue-rabbitmq:dev-master`

> **Side note**: 
As long there are no massages in the queue(s) or the queue(s) do not exist in rabbitMq, the worker(s)/consumer(s) should wait or time-out. In _most_ cases it's not the responsibility of a worker/consumer to create a queue. In most cases this is the responsibility of RabbitMq or the producer of the message.

**Comment by itsursujit** [comment]
@adm-bome The issue is I cannot run a consumer with multiple queue:
`php artisan rabbitmq:consume  --queue=store-to-db-queue,store-to-db-prio-3,store-to-db-prio-2,store-to-db-prio-1,store-to-db-prio-0`

**Comment by adm-bome** [comment]
Why not use the `php artisan queue:work`, `php artisan queue:listen` or use Horizon and its commands?

I don't see it as an problem or a bug. 
I will look into it, and maybe we can add this **feature** for the consumer provided with this library

**Comment by itsursujit** [comment]
queue:work for rabbitmq uses `basic_get` method which is less efficient than `basic_consume`

And looking for solution to allow a consumer consuming multiple queues like queue:work (normal commands) does

**Comment by adm-bome** [comment]
After some research....

It's not possible to switch between queues with `basic_consume`.
We can't tell `basic_consume` to work queues in a serial way.
The only option is to work queues in parallel. 

Ofcourse we can rewrite the consumer to be able to consuming queues in parallel way, when started with a single command and multiple queues defined in the options. 

But i'm not going to do so, because that's the same thing as starting multiple commands with one queue defined.

> `basic_consume` can't handle **prioritization queues** as stated in the documentation by laravel. So don't use this consumer as one that can ;) .
