### ISSUE TITLE
AMQP error while attempting pushRaw: Error sending data. Connection timed out.

### ISSUE THREAD

**Issue by ismailocal** [vyuldashev/laravel-queue-rabbitmq#330]
Laravel 5.8

Queue work

> php artisan queue:work --tries=3 --timeout=5000

Version

> "vladimir-yuldashev/laravel-queue-rabbitmq": "^8.3",

Can you help?

Process time

> [2020-04-10 14:17:44] local.INFO: start
> [2020-04-10 14:19:12] local.INFO: end

`{"error":"{\"xdebug_message\":\"\
Interop\\\\Queue\\\\Exception\\\\Exception: Error sending data. Connection timed out. in \\/home\\/ismail\\/projects\\/management\\/vendor\\/enqueue\\/amqp-lib\\/AmqpProducer.php on line 77\
\
Call Stack:\
    0.0001     390248   1. {main}() \\/home\\/ismail\\/projects\\/management\\/artisan:0\
    0.0393    6138264   2. App\\\\Console\\\\Kernel->handle() \\/home\\/ismail\\/projects\\/management\\/artisan:37\
    0.1834   29484128   3. Illuminate\\\\Console\\\\Application->run() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Console\\/Kernel.php:133\
    0.1835   29486856   4. Illuminate\\\\Console\\\\Application->run() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Console\\/Application.php:90\
    0.1896   29488184   5. Illuminate\\\\Console\\\\Application->doRun() \\/home\\/ismail\\/projects\\/management\\/vendor\\/symfony\\/console\\/Application.php:147\
    0.1901   29502808   6. Illuminate\\\\Console\\\\Application->doRunCommand() \\/home\\/ismail\\/projects\\/management\\/vendor\\/symfony\\/console\\/Application.php:271\
    0.1902   29502808   7. Illuminate\\\\Queue\\\\Console\\\\WorkCommand->run() \\/home\\/ismail\\/projects\\/management\\/vendor\\/symfony\\/console\\/Application.php:1001\
    0.1911   29684872   8. Illuminate\\\\Queue\\\\Console\\\\WorkCommand->run() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Console\\/Command.php:170\
    0.1913   29687512   9. Illuminate\\\\Queue\\\\Console\\\\WorkCommand->execute() \\/home\\/ismail\\/projects\\/management\\/vendor\\/symfony\\/console\\/Command\\/Command.php:255\
    0.1913   29687888  10. Illuminate\\\\Foundation\\\\Application->call() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Console\\/Command.php:183\
    0.1913   29687888  11. Illuminate\\\\Container\\\\BoundMethod::call() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Container\\/Container.php:576\
    0.1913   29688584  12. Illuminate\\\\Container\\\\BoundMethod::callBoundMethod() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Container\\/BoundMethod.php:34\
    0.1913   29688664  13. Illuminate\\\\Container\\\\BoundMethod::Illuminate\\\\Container\\\\{closure:\\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Container\\/BoundMethod.php:30-34}() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Container\\/BoundMethod.php:90\
    0.1914   29689040  14. call_user_func_array:{\\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Container\\/BoundMethod.php:32}() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Container\\/BoundMethod.php:32\
    0.1914   29689048  15. Illuminate\\\\Queue\\\\Console\\\\WorkCommand->handle() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Container\\/BoundMethod.php:32\
    0.1915   29693224  16. Illuminate\\\\Queue\\\\Console\\\\WorkCommand->runWorker() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Queue\\/Console\\/WorkCommand.php:86\
    0.1916   29697408  17. Illuminate\\\\Queue\\\\Worker->daemon() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Queue\\/Console\\/WorkCommand.php:102\
   54.6428   47757320  18. Illuminate\\\\Queue\\\\Worker->runJob() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Queue\\/Worker.php:118\
   54.6428   47757320  19. Illuminate\\\\Queue\\\\Worker->process() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Queue\\/Worker.php:283\
   54.6431   47757320  20. VladimirYuldashev\\\\LaravelQueueRabbitMQ\\\\Queue\\\\Jobs\\\\RabbitMQJob->fire() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Queue\\/Worker.php:337\
   54.6432   47764176  21. App\\\\Jobs\\\\OutputJob->fire() \\/home\\/ismail\\/projects\\/management\\/app\\/Override\\/Queue\\/RabbitMQJob.php:58\
   54.6432   47764176  22. App\\\\Jobs\\\\OutputJob->handle() \\/home\\/ismail\\/projects\\/management\\/app\\/Jobs\\/OutputJob.php:63\
   54.6467   47772552  23. App\\\\Domains\\\\Domain\\\\Action->run() \\/home\\/ismail\\/projects\\/management\\/app\\/Jobs\\/OutputJob.php:51\
   54.6467   47772552  24. App\\\\Domains\\\\Domain\\\\Action->execute() \\/home\\/ismail\\/projects\\/management\\/app\\/Domains\\/Domain\\/Action.php:24\
   54.6467   47772552  25. App\\\\Domains\\\\Domain\\\\Action->callWithTransaction() \\/home\\/ismail\\/projects\\/management\\/app\\/Domains\\/Domain\\/Action.php:34\
   54.6467   47773248  26. Illuminate\\\\Support\\\\Facades\\\\Facade::transaction() \\/home\\/ismail\\/projects\\/management\\/app\\/Domains\\/Domain\\/Action.php:97\
   54.6467   47773624  27. Illuminate\\\\Support\\\\Facades\\\\Facade::__callStatic() \\/home\\/ismail\\/projects\\/management\\/app\\/Domains\\/Domain\\/Action.php:97\
   54.6467   47773624  28. Illuminate\\\\Database\\\\DatabaseManager->transaction() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Support\\/Facades\\/Facade.php:239\
   54.6467   47774000  29. Illuminate\\\\Database\\\\DatabaseManager->__call() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Support\\/Facades\\/Facade.php:239\
   54.6468   47774000  30. Phaza\\\\LaravelPostgis\\\\PostgisConnection->transaction() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Database\\/DatabaseManager.php:349\
  130.2013   59493632  31. tap() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Database\\/Concerns\\/ManagesTransactions.php:31\
  130.2013   59493632  32. Phaza\\\\LaravelPostgis\\\\PostgisConnection->Illuminate\\\\Database\\\\Concerns\\\\{closure:\\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Database\\/Concerns\\/ManagesTransactions.php:29-31}() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Support\\/helpers.php:1124\
  130.2013   59493632  33. Phaza\\\\LaravelPostgis\\\\PostgisConnection->commit() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Database\\/Concerns\\/ManagesTransactions.php:30\
  130.2023   59493632  34. Phaza\\\\LaravelPostgis\\\\PostgisConnection->fireConnectionEvent() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Database\\/Concerns\\/ManagesTransactions.php:162\
  130.2024   59493712  35. Neves\\\\Events\\\\TransactionalDispatcher->dispatch() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Database\\/Connection.php:813\
  130.2024   59493712  36. Illuminate\\\\Events\\\\Dispatcher->dispatch() \\/home\\/ismail\\/projects\\/management\\/vendor\\/fntneves\\/laravel-transactional-events\\/src\\/Neves\\/Events\\/TransactionalDispatcher.php:114\
  130.2024   59494464  37. Illuminate\\\\Events\\\\Dispatcher->Illuminate\\\\Events\\\\{closure:\\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:342-348}() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:196\
  130.2024   59494464  38. Neves\\\\Events\\\\TransactionalDispatcher->Neves\\\\Events\\\\{closure:\\/home\\/ismail\\/projects\\/management\\/vendor\\/fntneves\\/laravel-transactional-events\\/src\\/Neves\\/Events\\/TransactionalDispatcher.php:346-348}() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:347\
  130.2024   59494464  39. Neves\\\\Events\\\\TransactionalDispatcher->onTransactionCommit() \\/home\\/ismail\\/projects\\/management\\/vendor\\/fntneves\\/laravel-transactional-events\\/src\\/Neves\\/Events\\/TransactionalDispatcher.php:347\
  130.2024   59494464  40. Neves\\\\Events\\\\TransactionalDispatcher->dispatchPendingEvents() \\/home\\/ismail\\/projects\\/management\\/vendor\\/fntneves\\/laravel-transactional-events\\/src\\/Neves\\/Events\\/TransactionalDispatcher.php:171\
  156.9373   59763344  41. Illuminate\\\\Events\\\\Dispatcher->dispatch() \\/home\\/ismail\\/projects\\/management\\/vendor\\/fntneves\\/laravel-transactional-events\\/src\\/Neves\\/Events\\/TransactionalDispatcher.php:224\
  156.9374   59764096  42. Illuminate\\\\Events\\\\Dispatcher->Illuminate\\\\Events\\\\{closure:\\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:360-368}() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:196\
  156.9378   59767584  43. call_user_func_array:{\\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:366}() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:366\
  156.9378   59767600  44. Illuminate\\\\Events\\\\Dispatcher->Illuminate\\\\Events\\\\{closure:\\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:425-433}() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:366\
  156.9378   59768072  45. Illuminate\\\\Events\\\\Dispatcher->queueHandler() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:431\
  156.9381   59768288  46. VladimirYuldashev\\\\LaravelQueueRabbitMQ\\\\Queue\\\\RabbitMQQueue->pushOn() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Events\\/Dispatcher.php:472\
  156.9381   59768288  47. VladimirYuldashev\\\\LaravelQueueRabbitMQ\\\\Queue\\\\RabbitMQQueue->push() \\/home\\/ismail\\/projects\\/management\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Queue\\/Queue.php:44\
  156.9631   62586360  48. VladimirYuldashev\\\\LaravelQueueRabbitMQ\\\\Queue\\\\RabbitMQQueue->pushRaw() \\/home\\/ismail\\/projects\\/management\\/vendor\\/vladimir-yuldashev\\/laravel-queue-rabbitmq\\/src\\/Queue\\/RabbitMQQueue.php:62\
  157.0994   62587568  49. Enqueue\\\\AmqpLib\\\\AmqpProducer->send() \\/home\\/ismail\\/projects\\/management\\/vendor\\/vladimir-yuldashev\\/laravel-queue-rabbitmq\\/src\\/Queue\\/RabbitMQQueue.php:121\
\"}"} `

**Comment by abubaker962** [comment]
Hi, Ismail, I am facing the same issue. How did you resolved it?
