### ISSUE TITLE
Configuring RabbitMQ to Laravel(PRECONDITION_FAILED)

### ISSUE THREAD

**Issue by beloofficial** [vyuldashev/laravel-queue-rabbitmq#331]
I must to get prices(its my task). To get them, I need to configure integration with RabbitMQ.
I use RMQ for laravel for the first time. that's what i did:
1) I have: Server address, virtual host, port, login, password and queue_name.
2) Everything except the last I wrote into config/queue.php
3) Created Job with "php artisan make:job ProcessPodcast" and I didnt know what to write inside(its my first problem)
4) In controller I have called:  ProcessPodcast::dispatch()->onQueue("queue_name");
5) From terminal: php artisan queue:work
6) So, when I am calling controller method. I have an error "PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'queue_name' in vhost 'vhost_name': received the value 'queue_name' of type 'longstr' but current is none"
-------------------------------------------------------------------------------------------------------
I must be doing something wrong, since I just started using this technology. Could you write briefly all steps that I must to do for this task. Thank you!

**Comment by vyuldashev** [comment]
Try v10.2.0

**Comment by adm-bome** [comment]
Please try the latest version v10.2.0

In rabbitMQ don't define or setup a queue. 
The library will do that for you. Depending on your config in laravel.

Will close the issue. Mainly because this is not a forum. :)
