### ISSUE TITLE
Can you list the all configuration

### ISSUE THREAD

**Issue by jlwgeneral** [vyuldashev/laravel-queue-rabbitmq#335]
excuse，I see a lot of configuration information on the Internet，and it's not the same，if you list the all standard，we can save a lot of time，thanks

**Comment by jlwgeneral** [comment]
for example, if I want to use 2 queue, I dont know how to do, now I know we need config 2 connection……

**Comment by adm-bome** [comment]
It all depends of your use cases.

The readme should explain the basic config and the optional config.

**Comment by jlwgeneral** [comment]
I know what you mean, but I mean  I want to know what I can configure

**Comment by adm-bome** [comment]
The ReadMe is there and everything is described within it. 
For information how Laravel works you should read there documentation or read the code.

If you have suggestions for better documentation your welcome to submit a PR.

Closing the issue mainly because this is not a forum.
