### ISSUE TITLE
Listen for non-job formatted messages (general messages)

### ISSUE THREAD

**Issue by etudor** [vyuldashev/laravel-queue-rabbitmq#338]
This may seem like a stupid question, but how can I listen for general messages?   
I have messages published on the rabbitmq queue from another application and I would like to handle them via a consumer/job handler/worker or anything. 

I managed to publish messages to the rabbitmq with the library so the connection is properly made. 
I am using laravel 7.13 (latest) and the latest version of this package as well.

This may not be necessarily a question for this package or Laravel framework.

Could I create an old type rabbitmq consumer? I don't necessarily need to create a job handler.
I would assume what I want to do is quite easy but haven't found the right answer yet.

I see that the same question is on StackOverflow but the answer is not very clear and I don't want to install another rabbitmq laravel package. https://stackoverflow.com/questions/32505501/consume-raw-json-queue-messages-in-laravel

Many thanks

**Comment by adm-bome** [comment]
What do you mean by a **general message**? 

Most of laravel consumers worker work the way laravel creates a payload. 
A typical payload would be:

```json
{
  "uuid": "6616c749-89a1-4d74-acfb-4ec26eb49794",
  "displayName": "App\\Jobs\\TestJob",
  "job": "Illuminate\\Queue\\CallQueuedHandler@call",
  "maxTries": null,
  "maxExceptions": null,
  "delay": null,
  "timeout": null,
  "timeoutAt": null,
  "data": {
    "commandName": "App\\Jobs\\TestJob",
    "command": "O:16:\"App\\Jobs\\TestJob\":8:{s:3:\"job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}"
  },
  "id": "8HCJIvi8qSCG7jOdDPelkj21p55pJEjb"
}
```

**Comment by etudor** [comment]
I mean a raw json message that is being published by a nodejs backend to Rabbitmq:
{"attr":"value"}

**Comment by adm-bome** [comment]
The consumers/workers can recreate the TestJob with parameters and handle/process the TestJob.

If your messages in RabbitMQ is not using this format (in the payload) you have to write your own consumer/worker.

What I would do is read the laravel code `Illuminate\Queue\Worker` class
you can read how the payload is made into a class. Or you can just make a worker with something as:

```php
$connectionName = 'rabbitmq';
$queueConnection = Queue::connection($connectionName)
$rabbitMQJob = $queueConnection->pop();
$payload = $rabbitMQJob->payload();


$job = app()->make(TestJob::class);  // Auto dependency injection 
$job->handle($payload);
```

**Comment by etudor** [comment]
This is the way I solved this 
I noticed that in the job class in laravel it resolves the message by the "job" property
```
    /**
     * Fire the job.
     *
     * @return void
     */
    public function fire()
    {
        $payload = $this->payload();

        [$class, $method] = JobName::parse($payload['job']);

        ($this->instance = $this->resolve($class))->{$method}($this, $payload['data']);
    }

...

    protected function resolve($class)
    {
        return $this->container->make($class);
    }
```

So, I updated my nodejs app to add a job property with a static value (my laravel service name) "my_service"
Example message:
```
{
  "job": "my_service",
  "data": {"my_data":"my data"}
}
```

Then I registered a service in the laravel container that will resolve the "my_service"

```
        $this->app->bind('my_service', function () {
            return new MyService();
        });
```

And my service 
```
class ProcessScrapingData
{
    public function fire(RabbitMQJob $job, $data)
    {
        var_dump($data);
        print('firing');
        $job->delete();
    }
}
```

**Comment by adm-bome** [comment]
Also a Nice solution ;) for your use case.
If u can alter the payload within your NodeJs App, you can of course always alter the payload by calling your job directly:

```json
{
  "job": "App\\Jobs\\TestJob@handle",
  "data": {
    "key": "value"
  }
}
```
This is without all the extra work with services ;)

> Note not tested...

**Comment by etudor** [comment]
Yep, true. 
Thanks :)

**Comment by vittorio-c** [comment]
Solution of @adm-bome works, but I've noticed that `php artisan queue:work` consumer needs an additional field `id` in order to proceed with the job. So the payload that I use is : 

```
{
	"job": "App\\Jobs\\TestJob@handle",
	"data": {
		"key1": "Value 1"
	},
	"id": "8HCJIvi8qSCG7jOdDPelkj21p55pJEjb"
}
```
