### ISSUE TITLE
Message lost when publishing to a delayed queue

### ISSUE THREAD

**Issue by joskfg** [vyuldashev/laravel-queue-rabbitmq#342]
- Laravel/Lumen version: 7.15.0
- RabbitMQ version: 3.7.17
- Package version: 10.2.1

**Describe the bug**

When the publisher writes a message directly to a delayed queue, the message is lost because the normal queue where the dead letter redirects doesn't exist

**Steps To Reproduce**

1. Start a consumer to the queue "my-messages"
2. Send a message with a delay to the "my-messages" queue
3. Wait until delay is over

**Current behavior**

- What happens with the worker?
The message never reach the worker
- Is the message gone?
Yes, the temporary queue after the expiration time resend the message to "my-messages", but that queue doesn't exist. Just the "my-messages.delay.xxxx" exist.

**Expected behavior**

Both queues (delayed and not) should be created, so when I publish a delayed message, the worker receives it after the expiration time.

**Additional context**

This is useful when you want to start a specific process with a delay.

**Comment by zhankenson** [comment]
Yes, I have the same problem.
The business needs me to use  delay queues. In Laravel, I try to use dispatch()->onQueue('test')->delay(time).
I ran php artisan queue:work rabbitmq --queue=test on the console.
But only temporary queues appear in the background of RabbitMQ,like test.delay.xxxxx.When the temporary queue expires and disappears, the consumer does not receive the message.
I don't know if I made a mistake or if it was a persistent problem.
Please help me.

**Comment by adm-bome** [comment]
**Workaround:**
Pre-define the queue within RabbitMQ ;)

I can see the use-case and will try to find a solution within the Laravel scope. But I think its not as easy.
Because of how the laravel Api works and there will be a trade off when doing an extra check for existence and creation of the queue.

I only tested this with both queue's present. So the workaround should work.

**Comment by zhankenson** [comment]
> **Workaround:**
> Pre-define the queue within RabbitMQ ;)
> 
> I can see the use-case and will try to find a solution within the Laravel scope. But I think its not as easy.
> Because of how the laravel Api works and there will be a trade off when doing an extra check for existence and creation of the queue.
> 
> I only tested this with both queue's present. So the workaround should work.



> **解决方法：**
> 在RabbitMQ中预定义队列;）
> 
> 我可以看到用例，并将尝试在Laravel范围内找到解决方案。但是我认为这并不容易。
> 由于laravel Api是如何工作的，因此在对队列的存在和创建进行额外检查时会有所取舍。
> 
> 我只在两个队列都存在的情况下对此进行了测试。因此，解决方法应该起作用。



> **Workaround:**
> Pre-define the queue within RabbitMQ ;)
> 
> I can see the use-case and will try to find a solution within the Laravel scope. But I think its not as easy.
> Because of how the laravel Api works and there will be a trade off when doing an extra check for existence and creation of the queue.
> 
> I only tested this with both queue's present. So the workaround should work.

Can you provide an example of Laravel using deferred queues?thanks

**Comment by joskfg** [comment]
You just need to use your current configuration of deferred queues, but you will need to execute once the command
```
php artisan rabbitmq:queue-declare <your-queue-name>
```

The problem with this workaround is that you need to execute this manually, so if you recreate your environment or deploying a new one, you need to execute it again.

**Comment by adm-bome** [comment]
Run the command via the laravel scheduler or direcly via cron. The command checks for existence.

**Comment by adm-bome** [comment]
@joskfg 
I think that in special cases like these, the 'workaround' becomes the 'solution'.
When adding a extra check into the library and run the creation for the queue, all use-cases suffer from the extra time consuming check/action.
So the process time of individual messages becomes less efficient, and when you have allot of messages this is not what you want.

**Comment by joskfg** [comment]
I think that create always both queues (delayed and original) when you are publishing to a delayed queue has almost 0 impacts.

**Comment by adm-bome** [comment]
> I think that create always both queues (delayed and original) when you are publishing to a delayed queue has almost 0 impacts.

Unfortunately that's not so true.
U can't declare a queue when it already exits. U get an exception when doing so.
So we must check for existence before declaring a queue. This is done against the RabbitMQ server and besides the round-trip-time, this costs 2 calls extra.

This is not so much a problem when u just dispatch a Job. But when working with a delay when jobs fail this is time consuming for the workers that process the messages.

A normal flow is you want to dispatch a Job and want to immediately consume/process the job. When the Job fails you can delay the job so the message in the queue won't block other messages from being consumed/processed.

When you have a thousand or more messages into the queue and every time you have to do the extra checks when a Job has to be delayed, the processing time of a message/Job will increase.
With a large queue this is allot of extra calls/round-trips when all Jobs fail and get delayed.

In the first solution i gave above, there will be only extra 'down-time', when publishing/dispatching to the queue. And not when consuming the queue with other processes/workers.

U minimize the downside like this.
Publishing/Dispatching a Job and Consuming/Processing a Job are two different things and should be separated.
The Consuming/Processing part should be as fast as possible.

**Comment by zhankenson** [comment]
> @joskfg
> I think that in special cases like these, the 'workaround' becomes the 'solution'.
> When adding a extra check into the library and run the creation for the queue, all use-cases suffer from the extra time consuming check/action.
> So the process time of individual messages becomes less efficient, and when you have allot of messages this is not what you want.
> 
> @zhankenson
> Hope above solutions, work for you

Thank you for your help,I tried to declare the queue and then run the delayed queue,it runs.But there was an error executing Artisan::call('rabbitmq:queue-declare', ['name' => 'test2 ']) in laravel:  The command "rabbitmq:queue-declare" does not exist.Is there anything else I need to do？

**Comment by adm-bome** [comment]
That because currently the commands are only registered when running in console mode.

Try calling it with the command signature:
```php
Artisan::call('rabbitmq:queue-declare test2');
```

I will add a PR for the commands to be available in the app.

**Comment by zhankenson** [comment]
> That because currently the commands are only registered when running in console mode.
> 
> Try adding the command in your kernel
> 
> ```
> // app/Console/Kernel.php
> protected $commands = [
>     \VladimirYuldashev\LaravelQueueRabbitMQ\Commands\QueueDeclareCommand::class,
> ];
> ```
> 
> and call it or call it with the command signature:
> 
> ```
> Artisan::call('rabbitmq:queue-declare test2');
> ```
> 
> I will add a PR for the commands to be available in the app.

thank you very much

**Comment by kafkiansky** [comment]
> **Option one:**
> When you dispatch a delayed job also run the command from within the same method.
> 
> ```
>     public function dispatchDelayedJob()
>     {
>         Artisan::call('rabbitmq:queue-declare', ['name' => $queueName]);
>         TestJob::dispatch()->onQueue($queueName)->delay($time);
>     }
> ```
> 
> **Option two:**
> When the job is constructed run the command
> 
> > The downside here:
> > It is time consuming. Every time you do something with the TestJob this is executed. Also when a worker handles the TestJob this command is executed.
> 
> ```
> <?php
> 
> namespace App\Jobs;
> 
> use Illuminate\Contracts\Queue\Job;
> 
> class TestJob
> {
>     /**
>      * Create a new job instance.
>      *
>      * @return void
>      */
>     public function __construct()
>     {
>         Artisan::call('rabbitmq:queue-declare', ['name' => $this->queue]);
>     }
> 
>     /**
>      * Execute the job.
>      *
>      * @param Job $job
>      * @param $data
>      *
>      * @return void
>      */
>     public function handle(Job $job, $data)
>     {
>         // ...
>     }
> }
> ```
> 
> **Option three:**
> Run the command via the laravel scheduler or direcly via cron when the system start's. The command checks for existence.
> 
> > Also:
> > Rabbitmq does not automatically remove queues so when the queue is present in RabbitMQ there should be no problem.
> > But if you want to be sure... You would run the command every x minutes, depending on your use-case.
> 
> > RabbitMQ also has an Management interface. From within this interface you can create an queue.

Don't use the options 1 and 2. When you call `Artisan::call` in same runtime where you dispatch the job, you increase connections count because console command also connect to broker same as current dispatcher. Use option 3 or, if you want some "automatization", you may do so:

```php
namespace App\Queue;

final class RabbitMQApplicationQueue extends RabbitMQQueue
{
    /**
     * @param int|\DateTimeInterface $delay
     * @param string|object $payload
     * @param string|null $queue
     * @param int $attempts
     *
     * @throws \PhpAmqpLib\Exception\AMQPProtocolChannelException
     *
     * @return string|int
     */
    public function laterRaw($delay, $payload, $queue = null, $attempts = 0)
    {
        if ($queue !== null) {
            $this->declareQueue($queue, true, false);
        }

        return parent::laterRaw($delay, $payload, $queue, $attempts);
    }
}
```

and sets the worker class in `config/queue.php`:

```php
 'worker' => env('RABBITMQ_WORKER', \App\Queue\RabbitMQApplicationQueue::class),
```
