### ISSUE TITLE
AMQP error while attempting pop: Channel connection is closed

### ISSUE THREAD

**Issue by smarcet** [vyuldashev/laravel-queue-rabbitmq#343]
- Laravel/Lumen version: 6
- RabbitMQ version: 3.8.5
- Package version: 9.0

got ramdoly this error messages

**AMQP error while attempting pop:
Channel connection is closed**

i checked the code for RabbitMQQueue::pop for version  9.0 and its not trying to re connect the channel

since version 10.0 tries reconnection

any chance to do the same for v9.0

**Comment by adm-bome** [comment]
Try to fork this lib and submit a PullRequest on the branch [v9.0]

@vyuldashev can you assist for this version.

**Comment by smarcet** [comment]
i would do that thx u 
regards
