### ISSUE TITLE
Queues are not created on horizon start up

### ISSUE THREAD

**Issue by sdapkus** [vyuldashev/laravel-queue-rabbitmq#350]
- Laravel version: v7.21.0
- RabbitMQ version: 3.3.5
- Package version: v10.2.2

**Describe the bug**

Recently I have updated my project from laravel 5.8 to laravel 7, together with that I updated horizon, and your package from v8.3.0 to v10.2.2. On previous setup when I start horizon all queues were created on startup, now queues are only created when I add jobs to that queue.

**Steps To Reproduce**

Start horizon and go to rabbitmq, there is no queues created.

**Current behavior**

It is working, but queues are not created on startup.
Rabbitmq log:
`rabbitmq_1    | =ERROR REPORT==== 24-Jul-2020::11:56:01 ===
rabbitmq_1    | connection <0.17961.0>, channel 2 - soft error:
rabbitmq_1    | {amqp_error,not_found,"no queue 'backend' in vhost '/'",'queue.declare'}`

**Expected behavior**

I expect that queues should create on horizon startup.

**Comment by adm-bome** [comment]
> **Expected behavior**
> 
> I expect that queues should create on horizon startup.

Don't ;)

Previous versions were wrong the way queues/workers were supposed to work. They were havily depending on The presence of RabbitMQ and available queues.
 
The workers could defined everything, that's very nice in development or when your not know what your doing. ;)
But eventually you want to have more control over what you do in rabbitMQ and you application.

> Oke, we can debate everything and its all a matter off context.

**Some explanation**
Workers are just workers and should only work a queue when it is available and if there are messages in that queue.
There is no need for an empty queue. When there is no queue there are no messages and also when u use exchanges and there is no queue bound to the exchange messages can be send by the application to rabbitMQ, but will be ignored and discarded.
This gives you more control and application(s) and message broker are separated and don't depend on each other.

When dispatching/publishing a Job/message to rabbitMQ, rabbitMQ must do the routing work for you. There are several ways to manage queues and exchanges so by default the library will check for presence of the queue. When there is no queue, one will be created against the direct (default) exchange. When working with exchanges u publish against routes.

**Mind set**
Don't depend on Horizon to create queues and exchanges for you, this is not what is horizon is about. Horizon is a Worker manager and workers don't define anything. The workers just work when needed.

**A solution**
When u want and cant find a sollution for not pre-declaring queues, u can pre-declare queues and exchanges by running the commands available in the console or via Artisan::call().

What i would do is to run a cron or Laravel schedular and run a set of commands. This seperates the application logic from the rabbitMQ configuration.
When you run into the situation you won't need the predeclaring anymore, you only have to disable the cron/schedular. without touching the application source.
