### ISSUE TITLE
The delay queue cannot run when the worker is horizon

### ISSUE THREAD

**Issue by zhankenson** [vyuldashev/laravel-queue-rabbitmq#351]
- Laravel/Lumen version: laravel:6.18.5
- RabbitMQ version: 3.8.5
- Package version: #.#.#

**Describe the bug**

I set worker as horizon and enabled the rabbitmq_delayed_message_exchange plug-in, but when executing the delay queue, I found that the delay queue could not be generated.
All delay queues are executed immediately.

**Expected behavior**

The delay queue can run when the worker is Horizon

**Additional context**

If there is an example laravel Horizon can use delay queue, please provide it. Thanks

**Comment by adm-bome** [comment]
At the moment there is no support for the Delay plugin.
Delaying messages is handled by Laravel not by the messagebroker.
