### ISSUE TITLE
Receiving Broken pipe or closed connection

### ISSUE THREAD

**Issue by sujit-baniya** [vyuldashev/laravel-queue-rabbitmq#354]
- Laravel/Lumen version: 6.3
- Package version: 10.2

**Describe the bug**

For long running job, I'm receiving error
`Broken pipe or closed connection` and then the consumer got killed

Exception caught here:

```php
try {
                $this->channel->wait(null, true, (int) $options->timeout);
            } catch (AMQPRuntimeException $exception) {
                $this->exceptions->report($exception);

                $this->kill(1);
            }
```

How should I fix this issue?

**Comment by murcoder** [comment]
According to this post https://lukasmestan.com/rabbitmq-broken-pipe-or-closed-connection/, you could try to add a heartbeat timeout to your _config/queue.php_:
   
```
'rabbitmq' => [
            //  [...]
            'options' => [
             
                'heartbeat' => env('RABBITMQ_HEARTBEAT', 30),
                'connection_timeout' => env('RABBITMQ_CONNECTION_TIMEOUT', 5.0),
            ],
        ],
```

**Comment by zaidhaider9** [comment]
@sujit-baniya Did this issue got fixed?

**Comment by sujit-baniya** [comment]
@zaidhaider9 it's still not fixed.

**Comment by zaidhaider9** [comment]
@sujit-baniya  was this for ssl or without ssl?

**Comment by sujit-baniya** [comment]
@zaidhaider9 it's for non-ssl. I've not tried with ssl though

**Comment by khepin** [comment]
Broken Pipe / closed connection errors will happen when your RabbitMQ server is experiencing issues and closed the connection with your consumer, or something in the network path prevents you from currently connecting to RabbitMQ. 

Having the consumer exit upon such failures is consistent with other Laravel Queue implementations. Here's what is usually done in such situations:
- Look into why the Rabbit host connection got closed if you can. But even with this, you have no guarantee this won't happen again.
- Run your consumer in a process manager. supervisord is a popular one that is used to restart processes that have failed under some circumstances. Depending where you run your consumers (kubernetes, cloud, ...), you might have other facilities to help you bring the process back up.
