### ISSUE TITLE
[10.2.2] Posibility to declare quorum queues.

### ISSUE THREAD

**Issue by Merhnferr** [vyuldashev/laravel-queue-rabbitmq#358]
At this moment only classic queues can be declared. It would be nice to have possibility to declare also quorum queues via artisan command or connection option.

Artisan command example:
`php artisan rabbitmq:queue-declare queue-name --quorum=1`

Connection config example:
```php
connections' => [
    // ...

    'rabbitmq' => [
        // ...

        'options' => [
            'queue' => [
                // ...

                'quorum' =>  true,
            ],
        ],
    ],

    // ...    
],
```
Possible solution: #359

**Comment by khepin** [comment]
Version 10 is not supported anymore. It's also worth noting this library no longer auto-creates queues for you. I would recommend you create your queues with the proper arguments and policies separate from this library.
