### ISSUE TITLE
Adding multiple queues in config file!

### ISSUE THREAD

**Issue by behzadbabaei** [vyuldashev/laravel-queue-rabbitmq#360]
- Laravel: 7.24
- RabbitMQ version: 3.6.10
- Package version: ^10.2

I'm trying to implement the services in which each service listens to one queue for an event.
I'm having one fanout exchange and that has two queues named order1.fanout and order2.fanout and I have bound each queue with one service by setting the  $queue and $connection in listener class.
The problem is how can I declare multiple queues in fanout exchange in the config file ( I could not find any help in documentation!) and I currently can only have one default queue in the config file?
Is there any possible solution for this?

**Comment by adm-bome** [comment]
What do you mean?

Get your naming correct. What exchanges, what are the queues and what are the routing keys. And what ar jobs.

I know the difference... but i can't make anything from your question. Is there a question or an issue?

Need more explanation in the good terminology

**Comment by adm-bome** [comment]
The default queue in the config nearly exists, to have a default queue when nothing is alltered by the Job or Dispatcher.

But i think you can configure a Job, to reflect what you want, when dispatching this Job.
configure a Job with properties as 'queue' and 'connection'
