### ISSUE TITLE
Laravel 8 / Horizon 5 > "Class 'Laravel\Horizon\JobId' not found" when dispatching a Job

### ISSUE THREAD

**Issue by julien-viard-infomaniak** [vyuldashev/laravel-queue-rabbitmq#362]
- Laravel 8.5
- RabbitMQ 3.8.8
- Package version: 11

**Describe the bug**

Simple job dispatch is not working:
DummyJob::dispatch(['dispatch' => 'dispatch']);

Same with a queue push:
Queue::push(new DummyJob(['push' => 'push']));

**Steps To Reproduce**

What steps needed, to reproduce this bug.

**Current behavior**

"Class 'Laravel\Horizon\JobId' not found"
vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php(536): VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue->getRandomId()

**Expected behavior**

With horizon 5 JobId class has gone, was here with horizon 4

**How to fix**

Adding class JobId and put an alias of App\\Library\\Horizon\\JobId is class does not exist.

**Comment by nathan-io** [comment]
We're also experiencing this issue.

vladimir-yuldashev/laravel-queue-rabbitmq v11.0.0
laravel/framework                         v8.4.0
RabbitMQ version: 3.8.7

**Comment by vyuldashev** [comment]
Fixed in 11.0.1
