### ISSUE TITLE
AWS MQ for RabbitMQ Connection Issue

### ISSUE THREAD

**Issue by talovicnedim** [vyuldashev/laravel-queue-rabbitmq#389]
Hi everyone,

First of all, I want to say thanks to everyone who contributed to this repo. The package works great on my local machine.

I don't know how familiar you are with recent AWS updates, but they announced that its Amazon MQ will now support RabbitMQ as well which sounds great! Here is more on that: https://aws.amazon.com/blogs/aws/amazon-mq-update-new-rabbitmq-message-broker-service/

I created a new instance (even tried with public access), but I always get something like this:

```
Exception 'PhpAmqpLib\Exception\AMQPConnectionClosedException' with message 'Broken pipe or closed connection' in /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:171
```

More info about the instance:

```
Broker engine
RabbitMQ

Deployment mode
Single-instance broker

Broker engine version
3.8.6

Public accessibility
Yes
```

I'm able to log into web dashboard. However, I'm not able to push jobs (which works on my local machine).

I know I haven't provided so much info, but I just wanted to check if anyone has experienced something similar? I'm not sure if I missed something.

Thanks!

**Comment by talovicnedim** [comment]
Ok, I found something. 

This package has a dependency on `php-amqplib/php-amqplib` and seems like that library uses AMPQ < 1.0 while Amazon uses AMPQ 1.0.

**Comment by tariksari** [comment]
You should probably use the following option

`'options' => [
                'context' => stream_context_create(['ssl' => ['' => '']]),       
 ],`

look at this :  https://github.com/stomp-php/stomp-php/issues/133#issuecomment-539871047

**Comment by talovicnedim** [comment]
@tariksari 
Thanks for the message! I switched the app to Redis, but I'll take a look into this once I find some time.

**Comment by talovicnedim** [comment]
@tariksari 
I had some time to check this and unfortunately I haven't been able to connect to Amazon MQ since the library uses `php-amqplib/php-amqplib` which doesn't support this.

**Comment by talovicnedim** [comment]
For those interested in this, you just need to set the following in your `queue.php`:

`'connection' => PhpAmqpLib\Connection\AMQPLazySSLConnection::class`

and it works. @tariksari
