### ISSUE TITLE
illuminate/queue error when installing the package

### ISSUE THREAD

**Issue by mubarak23** [vyuldashev/laravel-queue-rabbitmq#391]
- Laravel/Lumen version: 6.2
- RabbitMQ version: #.#.#
- Package version: 11.1.1

**Describe the bug**

- vladimir-yuldashev/laravel-queue-rabbitmq[v11.1.0, ..., v11.1.1] require illuminate/queue ^8.0 -> found illuminate/queue[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires vladimir-yuldashev/laravel-queue-rabbitmq ^11.1 -> satisfiable by vladimir-yuldashev/laravel-queue-rabbitmq[v11.1.0, v11.1.1].

**Steps To Reproduce**
composer require vladimir-yuldashev/laravel-queue-rabbitmq

What steps needed, to reproduce this bug.

**Current behavior**

- What happens with the worker?
- Is the message retried or put back into the queue?
- Is the message acknowledged or rejected?
- Is the message unacked?
- Is the message gone?

**Expected behavior**

What is the expected behavior

**Additional context**

Add any other context about the problem or describe the use-case.

**Comment by tariksari** [comment]
Try this  composer require vladimir-yuldashev/laravel-queue-rabbitmq:10.2.2

**Comment by vyuldashev** [comment]
Version 11 is for Laravel 8. Check README, please
