### ISSUE TITLE
Worker ignores `illuminate:queue:restart` signal

### ISSUE THREAD

**Issue by frans-beech-it** [vyuldashev/laravel-queue-rabbitmq#408]
- Laravel version: 8.26.1
- RabbitMQ version: 3
- Package version: 11.1.1

**Describe the bug**

After calling `queue:restart` the worker doesn't stop. 

**Steps To Reproduce**

1. Run `php artisan rabbitmq:consume`
2. Run in different terminal `php artisan queue:restart`

**Current behavior**

Worker ignores restart signal

**Expected behavior**

Worker should stop when `stopIfNecessary()` returns a exit code

**Additional context**

on https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/master/src/Consumer.php#L142 now the `stopIfNecessary()` is called. But the exit code isn't handled. It should break from the `while` loop and stop the "deamon"

```php
$this->stopIfNecessary($options, $lastRestart, $this->gotJob ? true : null);
```

should be changed to:

```php
            $status = $this->stopIfNecessary(
                $options, $lastRestart, $startTime, $jobsProcessed, $job
            );

            if (! is_null($status)) {
                return $this->stop($status);
            }
```

**Comment by MorrisonHotel** [comment]
@vyuldashev same problem.
We use systemd for workers, and systemd just killing the process with timeout exception on trying to restart service.

**Comment by khepin** [comment]
Version 11 of this package is no longer supported. If you are still experiencing the issue with a more recent version, please open a separate issue.
