### ISSUE TITLE
topic mode config

### ISSUE THREAD

**Issue by seniorYsir** [vyuldashev/laravel-queue-rabbitmq#410]
i used topic type in options.exchange config,as expected i saw the new exchange with topic type in my rabbitmq manager board,but how to add routing_key?i used the method as readme show,but didn't work.

**Comment by DriverCat** [comment]
Same here [https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/458](#458 )

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
