### ISSUE TITLE
Unable to run job as background on Laravel

### ISSUE THREAD

**Issue by Aamirpal** [vyuldashev/laravel-queue-rabbitmq#412]
- Laravel/Lumen version: #.#.#
- RabbitMQ version: #.#.#
- Package version: #.#.#

**Describe the bug**

**Steps To Reproduce**

What steps needed, to reproduce this bug.

**Current behavior**

- What happens with the worker?
- Is the message retried or put back into the queue?
- Is the message acknowledged or rejected?
- Is the message unacked?
- Is the message gone?

**Expected behavior**

What is the expected behavior

**Additional context**

Add any other context about the problem or describe the use-case.

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
