### ISSUE TITLE
The "rest" option does not exist

### ISSUE THREAD

**Issue by viandanteoscuro** [vyuldashev/laravel-queue-rabbitmq#413]
Hello,

I have the error "The "rest" option does not exist" when i launch php artisan rabbitmq:consume

Package version: 11.1.2

Do you have any suggestion?

Thanks

Massimo

**Comment by Demozo** [comment]
Same error on my end, this is with using the amqp-lib 3.0.0 RC version however, as such I didn't think to make an issue for it, since it is unsupported.

My composer.json (relevant part):
```
{
    "require": {
        "php-amqplib/php-amqplib": "3.0.0-rc2 as 2.12.3",
        "vladimir-yuldashev/laravel-queue-rabbitmq": "^11.1"
    }
}
```

**Comment by egonvb** [comment]
Bluntly added |{--rest=0 : Number of seconds to rest between jobs}" to $signature of  vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Console/ConsumeCommand.php
which seems to fix the problem.

**Comment by viandanteoscuro** [comment]
Thanks @egonvb it worked for me!
