### ISSUE TITLE
Custom exchange in pushRaw options

### ISSUE THREAD

**Issue by saiditec** [vyuldashev/laravel-queue-rabbitmq#418]
- Laravel/Lumen version: 6
- RabbitMQ version: 3.7
- Package version: 10.2.3

**Describe the bug**

Can't specify custom exchange in pushRaw function options parameters

**Steps To Reproduce**

```
 Queue::pushRaw($payload, null, [
            'exchange' => $event->exchange,
            'exchange_routing_key' => $event->exchange_routing_key
        ]);
```

**Current behavior**

the message not reaching the specified exchange (custom exchange other that the one in config file)

**Expected behavior**

Submit message to specified exchange

**Additional context**

this is a proposition to allow pushing to custom exchanges 

```
protected function publishProperties($queue, array $options = []): array
    {
        $queue = $this->getQueue($queue);
        $attempts = Arr::get($options, 'attempts') ?: 0;
        $exchange = Arr::get($options, 'exchange') ?: null;
        $exchangeRoutingKey = Arr::get($options, 'exchange_routing_key') ?: $queue;
        $destination = $this->getRoutingKey($exchangeRoutingKey);
        $exchange = $this->getExchange($exchange);
        $exchangeType = $this->getExchangeType();

        return [$destination, $exchange, $exchangeType, $attempts];
    }
```

**Comment by danileks** [comment]
+1

Need customizable option field

**Comment by dapeng235** [comment]
+1

**Comment by dapeng235** [comment]
I want to customize message routing key.

```
VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue

    public function push($job, $data = '', $queue = null)
    {
        $this->options['exchange_routing_key'] = $job->routingKey;
        return $this->pushRaw($this->createPayload($job, $queue, $data), $queue, $this->options);
    }
```

```
class DemoJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $connection = "demo";
    public $routingKey = "demo";
}
```

**Comment by DriverCat** [comment]
+1

**Comment by DriverCat** [comment]
> Queue::pushRaw($payload, null, [
>             'exchange' => $event->exchange,
>             'exchange_routing_key' => $event->exchange_routing_key
>         ]);

Could you please help me understand how to generate $payload for pushRaw?

**Comment by hakanersu** [comment]
I manage to make a work around [here](https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/458#issuecomment-1010274299)

**Comment by spider4216** [comment]
Hi there. I faced with that problem too. I'm using 11.2 version of this lib. Created [pull request](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/509) to provide 11 version of this lib custom exchange and routing key via options parameter. Hope it'll be merged and will be helpful.

@vyuldashev

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.

**Comment by spider4216** [comment]
This is still an open issue
