### ISSUE TITLE
[Bug] Artisan command keep running even if the consumer has exception with Broken Pipe

### ISSUE THREAD

**Issue by sujit-baniya** [vyuldashev/laravel-queue-rabbitmq#421]
- Laravel/Lumen version: latest
- RabbitMQ version: latest
- Package version: latest

**Describe the bug**
Whenever there's error on Connection and throw exception `php artisan rabbitmq:consume` doesn't stop or terminate. As the command is running, the monitoring tools like Supervisor doesn't know the status of consumer and consumers are not restarted.
Meanwhile this exception the there's no consumer on queue but Supervisor shows the process is running

**Steps To Reproduce**

Start the command `php artisan rabbitmq:consume` and externally trigger Broken Pipe or connection

**Expected behavior**

Whenever there's broken pipe exception, the artisan command should have been stopped or terminated

**Comment by bandgeekndb** [comment]
This behavior also is happening with Laravel Horizon. If something happens to the connection between the queue workers and the Rabbit server, my logs start filling up with:

`Broken pipe or closed connection {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPConnectionClosedException(code: 0): Broken pipe or closed connection at /var/www/servicebridge/vendor/php-amqp
lib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:172)`

and

`Channel connection is closed. {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPChannelClosedException(code: 0): Channel connection is closed. at /var/www/servicebridge/vendor/php-amqplib/php-a
mqplib/PhpAmqpLib/Channel/AbstractChannel.php:245)`

messages.

Terminating Horizon and letting supervisor or systemd restart the processes clears the errors (assuming connectivity has been reestablished between the queue workers and RabbitMQ).

**Comment by yurganov** [comment]
Hello, @bandgeekndb 

Did you manage to solve it?

**Comment by acosta-edgar** [comment]
We are observing the same problem, which also appears related to report #436 .
[This post explains how to catch possible connection exceptions](https://bestofphp.com/repo/php-amqplib-php-amqplib-php-queue#connection-recovery), I believe that is what needs to be done in `RabbitMQConnector::connect()` or `RabbitMQConnector::createConnection()`

**Comment by bandgeekndb** [comment]
@acosta-edgar Thanks for sharing this info, that's definitely helpful!

I'm not around next week, but when I get back, I'll fork this and see if I can add some connection recovery handling like you mentioned. If I can, I'll open a PR and see what the dev thinks!

**Comment by vyuldashev** [comment]
Should be fixed by #457
