### ISSUE TITLE
$tries and $backoff not working while job failed by timeout

### ISSUE THREAD

**Issue by jamesRUS52** [vyuldashev/laravel-queue-rabbitmq#423]
- Laravel/Lumen version: v8.38.0
- RabbitMQ version: RabbitMQ 3.8.16 Erlang 23.3.4
- Package version: v11.2.0 

**Describe the bug**

$tries and $backoff not working when job failed by timeout

**Steps To Reproduce**

job class with

    public $timeout = 20;
    public $tries = 3;
    public $backoff = [20,40];

job running time more then 20 sec

**Current behavior**

after job failed (after 20 sec) it execute again immediatly ($backoff not using) and infinite ($tries not using)

**Expected behavior**

the second attempt should be after 20 seconds from failed first time
the third attempt should be after 40 seconds from failed second time

**Additional context**

Add any other context about the problem or describe the use-case.

**Comment by yiiman-dev** [comment]
i need to solve this problem too
any solution?

**Comment by M-Porter** [comment]
Much like you, at the time I couldn't figure it out either. But I was easily able to come up with a solution that worked for my needs.

https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/456
