### ISSUE TITLE
How to instantiate RabbitMQJob in the schedule.

### ISSUE THREAD

**Issue by helveden** [vyuldashev/laravel-queue-rabbitmq#425]
I instantiate like this:

$schedule->job(new RabbitMQJob())->everyMinute();

Of course, I understand that I have to put arguments in the construct of the RabbitMQJob object, but I don't understand how I have to do it ?

I have errors 
public function __construct(
 Container $container,
 RabbitMQQueue $rabbitmq,
 AMQPMessage $message,
 string $connectionName
)
Cordialy

**Comment by kafkiansky** [comment]
@helveden, what do you expect from scheduling the `RabbitMQJob`? You need schedule your job, not the `RabbitMQJob`.

**Comment by khepin** [comment]
If you are looking to schedule a specific queued job, I suggest reading the Laravel documentation on the topic: https://laravel.com/docs/9.x/queues#dispatching-jobs
