### ISSUE TITLE
Error: PRECONDITION_FAILED - unknown delivery tag 1

### ISSUE THREAD

**Issue by uenucom** [vyuldashev/laravel-queue-rabbitmq#426]
- Laravel/Lumen version: 8.48.2
- RabbitMQ version:  3.8.3
- Package version: 11.2.0

**Describe the bug**

php artisan queue:work --daemon --sleep=3 --tries=3 --timeout=60 

local.ERROR: PRECONDITION_FAILED - unknown delivery tag 1 {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPProtocolChannelException(code: 406): PRECONDITION_FAILED - unknown delivery tag 1 at /home/www/laravel8/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:216)
[stacktrace]
#0 [internal function]: PhpAmqpLib\\Channel\\AMQPChannel->channel_close()
#1 /home/www/laravel8/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): call_user_func()
#2 /home/www/laravel8/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\\Channel\\AbstractChannel->dispatch()
#3 /home/www/laravel8/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1067): PhpAmqpLib\\Channel\\AbstractChannel->wait()
#4 /home/www/laravel8/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php(236): PhpAmqpLib\\Channel\\AMQPChannel->basic_get()
#5 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Queue/Worker.php(345): VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue->pop()
#6 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Queue/Worker.php(354): Illuminate\\Queue\\Worker->Illuminate\\Queue\\{closure}()
#7 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Queue/Worker.php(159): Illuminate\\Queue\\Worker->getNextJob()
#8 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#9 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#10 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#11 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#15 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#16 /home/www/laravel8/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#17 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#18 /home/www/laravel8/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#19 /home/www/laravel8/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#20 /home/www/laravel8/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#21 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#22 /home/www/laravel8/vendor/laravel/framesrc/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#23 /home/www/laravel8/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#24 {main}

**Comment by JMuGT3** [comment]
I have the same problem with 10.2.3.
Weird thing is the exact same job would sometimes execute ok after some time (as in: the job errors with the PRECONDITION_FAILED - unknown delivery tag 1 error, is sent back to queue, and if I retry the job a few times at it will sometimes execute correctly).

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
