### ISSUE TITLE
Undefined function RabbitMQQueue::clear() when called horizon:clear command

### ISSUE THREAD

**Issue by pankajjha** [vyuldashev/laravel-queue-rabbitmq#430]
- Laravel/Lumen version: 8.36.2
- RabbitMQ version: 3.8.17
- Package version: 11.2.0

**Describe the bug**

Hello, I was trying to clear all the pending jobs from my queue managed by Horizon using `php artisan horizon:clear` but it gives me following error

```
Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue::clear()

  at vendor/laravel/horizon/src/Console/ClearCommand.php:53
     49▕         $connection = Arr::first($this->laravel['config']->get('horizon.defaults'))['connection'] ?? 'redis';
     50▕ 
     51▕         $jobRepository->purge($queue = $this->getQueue($connection));
     52▕ 
  ➜  53▕         $count = $manager->connection($connection)->clear($queue);
     54▕ 
     55▕         $this->line('Cleared '.$count.' jobs from the ['.$queue.'] queue ');
     56▕ 
     57▕         return 0;

      +13 vendor frames 
  14  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
```

**Steps To Reproduce**

I tried using `php artisan horizon:clear` when I got this error.

I tried `php artisan queue:clear` but it says `Clearing queues is not supported on [RabbitMQQueue]`

**Current behavior**

Throwing undefined method call error, and the horizon is still showing the pending jobs but in rabbitMQ there is no message pending

**Expected behavior**

It should have cleared queue from both rabbitmq and Horizon redis

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
