### ISSUE TITLE
 Class 'Interop\Amqp\AmqpTopic' not found

### ISSUE THREAD

**Issue by o2-web** [vyuldashev/laravel-queue-rabbitmq#431]
- Laravel/Lumen version: 5.8
- Package version: 7.2.0

Sorry, i dont know english. Please help me

**Comment by malisoft** [comment]
Run: rm -rf vendor
Add to composer.json ->         "enqueue/amqp-bunny": "^0.10.9",
Run: composer install

**Comment by malisoft** [comment]
first delete tu vendor folder with: rm -rf vendor, so also delete composer.lock, after install these dependencies with:
composer require enqueue/amqp-bunny "^0.10.9" vladimir-yuldashev/laravel-queue-rabbitmq "^12.0"

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
