### ISSUE TITLE
In Consumer.php line 85: Call to undefined method Illuminate\Queue\NullQueue::getChannel()

### ISSUE THREAD

**Issue by lyubingo** [vyuldashev/laravel-queue-rabbitmq#433]
as the title says: 
when I use " php artisan rabbitmq:consume " it shows me:
```
In Consumer.php line 85: 
Call to undefined method Illuminate\Queue\NullQueue::getChannel().
```
what should I do ?

I have the file " config/queue.php " , which copy from here. 

and still add .env like this : 
```
QUEUE_CONNECTION=rabbitmq
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_VHOST=/
RABBITMQ_LOGIN=guest
RABBITMQ_PASSWORD=gutest
RABBITMQ_QUEUE=anywords
```
what I use is lumen 8, I didn't see anybody got this error , why ?

**Comment by lyubingo** [comment]
someone help me, I have locked here for a long time .

**Comment by zenire** [comment]
Specify the name of the connection in queue.php

**Comment by wasinr** [comment]
Hi,

I got the same issue, how to fixed this? currently connection in queue.php is

` 'connection' => PhpAmqpLib\Connection\AMQPLazyConnection::class,`

**Comment by roshandelpoor** [comment]
> QUEUE_CONNECTION=rabbitmq

work for me
thank you
