### ISSUE TITLE
bug for same name job between consumer and producer

### ISSUE THREAD

**Issue by dmolaie** [vyuldashev/laravel-queue-rabbitmq#434]
method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "User\Jobs\UserDataJob" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition

this error for different of namespace jobs between producer and consumer. why can not be different 
 name.

![Screenshot from 2021-08-08 18-34-16](https://user-images.githubusercontent.com/18552727/128634732-44265895-606d-432d-b363-270ad1cae915.png)

**Comment by M-Porter** [comment]
Laravel has a very explicit naming schema you must follow. If you product a job from one class, it expects that the `handle()` function will exist in that same class.

Closing as not a library issue.
