### ISSUE TITLE
ERROR: Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::readyNow() {"exception":"[object] (Error(code: 0): Call to undefined method VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue::readyNow() at vendor/laravel/horizon/src/WaitTimeCalculator.php:142) ALSO AutoScaler:82

### ISSUE THREAD

**Issue by WitchesKitchen** [vyuldashev/laravel-queue-rabbitmq#439]
- Laravel/Lumen version: Laravel v8.53.1
- RabbitMQ version: 3.8.2
- Package version: v11.3.0
- Horizon version: v5.7.10

**Describe the bug**

Consumer works as expected, but 2 errors are thrown :

`Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::readyNow() {"exception":"[object] (Error(code: 0): Call to undefined method VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue::readyNow() at/vendor/laravel/horizon/src/WaitTimeCalculator.php:142) `
`Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::readyNow() {"exception":"[object] (Error(code: 0): Call to undefined method VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue::readyNow() at /vendor/laravel/horizon/src/AutoScaler.php:82)`

**Steps To Reproduce**

- Create a custom class  including the payload method with array keys job and data to create a valid payload (the source payload isn't)
- define that class in the queue connection config
- set worker (RABBITMQ_WORKER) to default 
- do not use rabbitmq:consume, let Horizon start the consume worker 

**Current behavior**

- worker startet by Horizon
- message received and processed
- the 2 errors are thrown and written in the log file

**Additional context**

We need this configuration because we have smoothly running jobs, controlled by Horizon. The additional rabbitmq consumer needs to consume third party payload, that is not respecting Laravels payload scheme, but has to have an integration in the existing job Configuration

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.

**Comment by ALTELMA** [comment]
Currently this issue still happen and I was facing this now with Laravel v10.x and Horizon v5.3.x.
