### ISSUE TITLE
Can not connect rabbitmq container to laravel app

### ISSUE THREAD

**Issue by Nesma-m7md** [vyuldashev/laravel-queue-rabbitmq#442]
Hi,
I've write docker-compose.yml
Like this:

version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-docker/app:latest
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 
                your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    
    rabbitmq:
       image: 'bitnami/rabbitmq:latest'
       Container_name: rabbitmq
       restart:unless-stopped
       tty: true
       ports:
          - "15672:15672"
          -  "5672:5672"
       networks:
          - app-network
          
#Docker Networks
networks:
  app-network:
    driver: bridge

×××××××
Put rabbitmq is not really connected to my laravel what i'm missing

I installed laravel:
git clone https://github.com/laravel/laravel.git

Tried your command for laravel rabbitmq but didn't work for my compose file

Really don't now where the error

**Comment by M-Porter** [comment]
This is unrelated to the library.

In docker your rabbitmq host name is `rabbitmq`. So set `RABBITMQ_HOST=rabbitmq`.
