### ISSUE TITLE
RabbitMQQueue does not raise JobQueued event

### ISSUE THREAD

**Issue by rnixik** [vyuldashev/laravel-queue-rabbitmq#443]
- Laravel version: 8.51.0
- RabbitMQ version: 3.8.19
- Package version: 11.3.0

`RabbitMQQueue` does not raise `\Illuminate\Queue\Events\JobQueued` event from `push` and `later` methods.

**Steps To Reproduce**

Add event listener for JobQueued, dispatch job.

**Current behavior**

Event is not fired.

**Expected behavior**

Event is fired.

**Additional context**

RedisQueue uses this to raise events:
```
public function push($job, $data = '', $queue = null)
    {
        return $this->enqueueUsing(
            $job,
            $this->createPayload($job, $this->getQueue($queue), $data),
            $queue,
            null,
            function ($payload, $queue) {
                return $this->pushRaw($payload, $queue);
            }
        );
    }
```

**Comment by khepin** [comment]
Gonna close this due to inactivity and the package version no longer being supported. It should be fixed in newer versions.
