### ISSUE TITLE
Octet out of range on dispatching job

### ISSUE THREAD

**Issue by iamwebdev** [vyuldashev/laravel-queue-rabbitmq#445]
- Laravel/Lumen version: 8.0
- RabbitMQ version: 11
- Package version: 11

 On dispatching job i am getting following error:
[https://prnt.sc/1y1fnv7](url)

**Comment by professor93** [comment]
Have you found any solutions?
@iamwebdev @vyuldashev

**Comment by iamwebdev** [comment]
> Have you found any solutions? @iamwebdev @vyuldashev

Not yet, how come not anyone else facing this issue. It is pretty common

**Comment by khepin** [comment]
Due to the lack of activity here and the lack of details (non functional link in PR), I'm gonna close this PR. Feel free to open a new one or re-open this one if you have more details that we could work from.

**Comment by DushyanthaHerath** [comment]
This happens if you set  queue priority in queue job. Solution is to use,

dispatch()->onQueue('priority');

or set in constructor
