### ISSUE TITLE
How to consume the dead letter queue

### ISSUE THREAD

**Issue by qq2161811** [vyuldashev/laravel-queue-rabbitmq#448]
- Laravel/Lumen version: laravel 8.0
- RabbitMQ version: 3.9.3
- Package version: 11.3

failed_exchange and failed_routing_key have been set in the configuration. 
How to specify the correct queue for consumption? 
Now it is consumed in the wrong queue

![image](https://user-images.githubusercontent.com/31003386/141882901-0850beba-3fe4-47bc-82e2-d6ed0dbba5b2.png)

Correct queue：App\Jobs\DeadMessageJob

How to correctly consume the dead letter queue?

**Comment by BehroozBvk** [comment]
This is my problem too. Does anyone know?

**Comment by khepin** [comment]
Try: `php artisan queue:work rabbitmq --queue $name_of_the_dead_letter_queue` (also works with `rabbitmq:consume`)
