### ISSUE TITLE
Autocreate queue

### ISSUE THREAD

**Issue by asvechkar** [vyuldashev/laravel-queue-rabbitmq#454]
When I change parameter RABBITMQ_QUEUE, I get error: queue *** dosn't exists. How to make new queue automaticaly?

**Comment by soulcodex** [comment]
This feature have a PR  opened #453 but the package owner still out of attend the incoming PR :cry:

**Comment by M-Porter** [comment]
Seems to have been removed between v9 and v10.

Other laravel queue libraries (e.g. sqs) do not auto generate queues as well.

My recommendation is to make sure you define your queues as part of your deploy using the `rabbitmq:queue-declare` artisan command.

**Comment by adm-bome** [comment]
Publishers:  are responsible for creating queues.
Consumers just consume when queues exist with messages. 

> Consumers must die when there is nothing to consume.
