### ISSUE TITLE
Working with TOPIC exchange in laravel-way

### ISSUE THREAD

**Issue by DriverCat** [vyuldashev/laravel-queue-rabbitmq#458]
Thank you for the package! I don't get how to work with TOPIC exchange in laravel way. 

1. How do I dispatch a job with a routing_key?
2. How do I bind queues to exchange with a routing key?

I would appreciate if you provide some examples on how to dispatch job with routing key and how to make consumer to listen exact keys (audit.*).

**Comment by amiranbarigreenweb** [comment]
That is our question too!!

**Comment by DriverCat** [comment]
Found out a little info:

1. I suppose, this package currentle doesnt support dynamic routing_key, only set up from config. For now it supports exchange and exchange_type dynamic binding for messages, but for this to work we need to use 
`Queue::pushRaw($payload, $queue, $options = ['exchange_type' => 'topic', 'exchange' => 'my_exchange'])` 
instead of dispatch. But I cant also figure out how to generate $payload in laravel format?
2. For now only option is to bind a queue to the exchange is with artisan command:
`php artisan rabbitmq:queue-bind my_queue my_exchange --routing_key=my_routing_key`
and then we can start our consumers to listen to this queue.

**Comment by amiranbarigreenweb** [comment]
@DriverCat  Thank you!

**Comment by amiranbarigreenweb** [comment]
@DriverCat  payload is easy - just push a message and then in rabbitMQ management you can see that payload in specific queue

**Comment by amiranbarigreenweb** [comment]
@DriverCat  multi queue is not very important - in fact each consumer should have one queue - so it is ok!

**Comment by amiranbarigreenweb** [comment]
@DriverCat  multi queue is not very important - in fact each consumer should have one queue - so it is ok!

**Comment by DriverCat** [comment]
> @DriverCat payload is easy - just push a message and then in rabbitMQ management you can see that payload in specific queue

I mean, is there any laravel function to generate it and send with pushRaw? Or do I need to generate it's format manually?


> @DriverCat multi queue is not very important - in fact each consumer should have one queue - so it is ok!

Yeah, it's acceptable for most cases.

**Comment by hakanersu** [comment]
I don't understand why but just routing key is not dynamic other options is dynamic so i manage to work find a work around.

FIrst of all problem is `getRoutingKey` method which is not using passed options in `pushRaw` method. So i decide to overwrite that class.

First of all i exclude class from autoload in composer.json

```json
 "autoload": {
        "exclude-from-classmap": [
            "VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue"
        ],
        "files": [
            "app/Overrides/RabbitMQQueue.php",
        ],
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
```

Copy RabbitMQQueue.php from vendor to suitable place. I use `app\Overwrites\RabbitMQQueue.php`

Changed `getRoutingKey` method with below below.

```php
    protected function getRoutingKey(string $destination, array $options = []): string
    {
        $options = array_merge($this->options, $options);

        return ltrim(sprintf(Arr::get($options, 'exchange_routing_key') ?: '%s', $destination), '.');
    }
```

and `publishProperties` method  with below;


```php
   protected function publishProperties($queue, array $options = []): array
    {
        $queue = $this->getQueue($queue);
        $attempts = Arr::get($options, 'attempts') ?: 0;

        $destination = $this->getRoutingKey($queue, $options);
        $exchange = $this->getExchange(Arr::get($options, 'exchange'));
        $exchangeType = $this->getExchangeType(Arr::get($options, 'exchange_type'));
        return [$destination, $exchange, $exchangeType, $attempts];
    }
```

Finally i can use dynamic routing keys;

```php
Queue::connection('rabbitmq')->pushRaw(json_encode([
    "event_type" => "number_operations",
    "action" => "add",
    "id" => $number->id,
], JSON_THROW_ON_ERROR), config('queue.connections.rabbitmq.queue'), [
    'exchange' => 'application-x',
    'exchange_type' => 'topic',
    'exchange_routing_key' => "gw:" . $number->gateway_id,
]);

**Comment by DriverCat** [comment]
@hakanersu Great workaround, thank you!

**Comment by amiranbarigreenweb** [comment]
I want to use push method not pushRaw - what is your idea about this? Thanks
@hakanersu @DriverCat

**Comment by hakanersu** [comment]
`push` method is uses Laravel's default structure so if your listeners is also Laravel i think you can use without problem. My queue workers are not Laravel so i need to use `pushRaw`

But there is no way to add options to `push` method so if you want to pass options, you have to modify `push` method like i did in previous comment.

Default push method;
```php
   public function push($job, $data = '', $queue = null)
    {
        return $this->pushRaw($this->createPayload($job, $queue, $data), $queue, []);
    }
```

Possible solution;

```php
    public function push($job, $data = '', $queue = null, array $options = [])
    {
        return $this->pushRaw($this->createPayload($job, $queue, $data), $queue, $options);
    }
```

**Comment by amiranbarigreenweb** [comment]
Thanks - yes my worker is laravel. i think we can't change push method because it Follow a contract
@hakanersu

**Comment by DriverCat** [comment]
@hakanersu Do you plan to make a PR with your routing key implementation?

**Comment by amiranbarigreenweb** [comment]
@hakanersu Thanks.

**Comment by montazericollege** [comment]
Hi, cant we have a property in out job named routing_key then our dispatcher, dispatch with that routing key  ?

**Comment by amiranbari** [comment]
This issue is really important.

**Comment by amiranbari** [comment]
There is a solution for this :
have a public property named $routingKey in your laravel job with value of your routingKey.
Then in change this methods in RabbitMQQueue.php file : 
`public function push($job, $data = '', $queue = null)
    {
        $options = [
            'exchange_routing_key'  =>  optional($job)->routingKey
        ];
        return $this->pushRaw($this->createPayload($job, $queue, $data), $queue, $options);
    }`

And

`protected function getRoutingKey(string $destination, array $options = []): string
    {
        $options = array_merge($this->options, $options);

        return ltrim(sprintf(Arr::get($options, 'exchange_routing_key') ?: '%s', $destination), '.');
    }`

And the last method : 
`protected function publishProperties($queue, array $options = []): array
    {
        $queue = $this->getQueue($queue);
        $attempts = Arr::get($options, 'attempts') ?: 0;

        $destination = $this->getRoutingKey($queue, $options);
        $exchange = $this->getExchange(Arr::get($options, 'exchange'));
        $exchangeType = $this->getExchangeType(Arr::get($options, 'exchange_type'));
        return [$destination, $exchange, $exchangeType, $attempts];
    }`

then your job will dispatch with exact routing key that you set

**Comment by montazericollege** [comment]
We can use onQueue method too. For example :
`(new (ExampleJob))->onQueue('routing_key_here');`

**Comment by khepin** [comment]
This last answer is correct, the `queue` is the `routing key`.
