### ISSUE TITLE
Rpc listen after job queued

### ISSUE THREAD

**Issue by amiranbarigreenweb** [vyuldashev/laravel-queue-rabbitmq#464]
Hi, we need to listen the reply queue in rpc after dispatching a job
like this: dispatch(New ExampleJob());
we want listen to reply in dispatch but i have no idea about this.
Do you have any idea?
Thanks

**Comment by leonrenkema** [comment]
When you wait for a job to complete it is easier to execute it direct. Or let the ExampleJob send a ExampleFinishedJob when something needs to happen when the first job is finished.

https://www.rabbitmq.com/tutorials/tutorial-six-python.html see "a note on RPC" why RPC is not a really good idea.

**Comment by M-Porter** [comment]
RPC is not a planned part of this library. You can setup laravel events to listen to changes or add triggers to your own Jobs to make RPC requests.
