### ISSUE TITLE
Лара 9

### ISSUE THREAD

**Issue by KatalinKS** [vyuldashev/laravel-queue-rabbitmq#466]
Добрый день, подскажите, когда будет добавлена поддержка Laravel 9

**Comment by R0dgerV** [comment]
https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/463

**Comment by Gildus** [comment]
https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/467

**Comment by vyuldashev** [comment]
Laravel 9 support has been released
