### ISSUE TITLE
PhpAmqpLib\Exception\AMQPRuntimeException: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.It is set to 1024, but you have descriptors numbered at least as high as 1324.--enable-fd-setsize=2048 is recommended, but you may want to set itto equal the maximum number of open files supported by your system,in order to avoid seeing this error again at a later date.

### ISSUE THREAD

**Issue by shifas05** [vyuldashev/laravel-queue-rabbitmq#469]
PhpAmqpLib\Exception\AMQPRuntimeException: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.It is set to 1024, but you have descriptors numbered at least as high as 1324.--enable-fd-setsize=2048 is recommended, but you may want to set itto equal the maximum number of open files supported by your system,in order to avoid seeing this error again at a later date.

"vladimir-yuldashev/laravel-queue-rabbitmq": "^11.3",
"laravel/framework": "v8.42.1",

Can anyone give me suggestion to fix this error , This is happening in production server.

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
