### ISSUE TITLE
Binding new Topic to Queue

### ISSUE THREAD

**Issue by atila-rampazo** [vyuldashev/laravel-queue-rabbitmq#476]
- Laravel/Lumen version: 8.65
- RabbitMQ version: 3
- Package version: ^11.3

**Describe the bug**

I'll need to use an "exchange" topi different from the default, I configure it in the queue.php, it appears in the rabbit dashboard, but the queue doesn't enter, I couldn't bind the queue with the new topic.

I didn't find it in the documentation.

**Comment by khepin** [comment]
Suggest you create the queues outside of this library. This is the approach taken by other Laravel queue drivers like SQS too: queue creation is done outside of the queue driver and is up to the developer.
