### ISSUE TITLE
laravel/framework replaces illuminate/queue and thus cannot coexist with it.

### ISSUE THREAD

**Issue by zibuyu888** [vyuldashev/laravel-queue-rabbitmq#477]
- vladimir-yuldashev/laravel-queue-rabbitmq v12.0.0 requires illuminate/queue ^9.0 -> satisfiable by illuminate/queue[v9.0.0-beta.1, ..., 9.x-dev].
    - Only one of these can be installed: illuminate/queue[v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v8.40.0, ..., 8.x-dev]. laravel/framework replaces illuminate/queue and thus cannot coexist with it.

**Comment by atila-rampazo** [comment]
Hi, man!

i'm using this version and work for me 

`"vladimir-yuldashev/laravel-queue-rabbitmq": "^11.3"`

**Comment by M-Porter** [comment]
Closed due to inactivity.
