### ISSUE TITLE
How to change failed jobs driver to redis?

### ISSUE THREAD

**Issue by BehroozBvk** [vyuldashev/laravel-queue-rabbitmq#478]
Hi, how can I change the driver of failed jobs to redis in rabbitmq? If the QUEUE_CONNECTION is on rabbitmq

**Comment by M-Porter** [comment]
Hi @BehroozBvk.

The best solution for this is to override the `queue.failed` container with your own implementation of the  [FailedJobProviderInterface](https://github.com/laravel/framework/blob/bce222337fe66ddea035cf21d05b4a3d97d15bbc/src/Illuminate/Queue/Failed/FailedJobProviderInterface.php).

Here is the laravel code for how failed jobs are written to the database. https://github.com/laravel/framework/blob/bce222337fe66ddea035cf21d05b4a3d97d15bbc/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php#L9

**Comment by M-Porter** [comment]
This is a great question but unfortunately it has nothing to do with the library itself so I am going to close it.
