### ISSUE TITLE
How to set uri to connect with other server?

### ISSUE THREAD

**Issue by uncannyMBM** [vyuldashev/laravel-queue-rabbitmq#481]
- Laravel/Lumen version: #.#.#
- RabbitMQ version: #.#.#
- Package version: #.#.#

**Describe the bug**

**Steps To Reproduce**

What steps needed, to reproduce this bug.

**Current behavior**

- What happens with the worker?
- Is the message retried or put back into the queue?
- Is the message acknowledged or rejected?
- Is the message unacked?
- Is the message gone?

**Expected behavior**

What is the expected behavior

**Additional context**

Add any other context about the problem or describe the use-case.

**Comment by M-Porter** [comment]
Closing due to insufficient information in question.
