### ISSUE TITLE
Headers Exchange / Dispatching

### ISSUE THREAD

**Issue by lucianocn** [vyuldashev/laravel-queue-rabbitmq#483]
Hi,
We use header exchange for message filtering, so I would like to know how you can add dynamic headers to dispatched messages.

```
class MyJob implements ShouldQueue
{
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    protected array $data;

    /**
     * Create a new job instance.
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        // Handle ($this->data)...
    }
}

```

Message Dispatching (adding headers like `X-HEADER1`: `FOO`, `X-HEADER2`: `BAR`).
`dispatch(new MyJob($data));`

**Comment by khepin** [comment]
You can provide your own implementation of `RabbitMQQueue` to add headers. I have done something like this to gzip payloads and add a `content_type: gzip` header to messages.
Overriding the `createMessage` function as done [here](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/447/files#diff-4c30c35d5db9a217457815591537a8db53a7769032470cb8bd3aad150bdaf6f8R553) for example.
