### ISSUE TITLE
Installing latest version on laravel 9

### ISSUE THREAD

**Issue by amiranbari** [vyuldashev/laravel-queue-rabbitmq#490]
Hi, when i want to install latest version on laravel 9 , I got some error  :

Problem 1
    - vladimir-yuldashev/laravel-queue-rabbitmq[dev-master, v13.0.0, ..., v13.0.1] require illuminate/queue ^9.0 -> found illuminate/queue[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - vladimir-yuldashev/laravel-queue-rabbitmq 13.0.x-dev is an alias of vladimir-yuldashev/laravel-queue-rabbitmq dev-master and thus requires it to be installed too.
    - Root composer.json requires vladimir-yuldashev/laravel-queue-rabbitmq ^13.0 -> satisfiable by vladimir-yuldashev/laravel-queue-rabbitmq[v13.0.0, v13.0.1, 13.0.x-dev (alias of dev-master)].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require vladimir-yuldashev/laravel-queue-rabbitmq:*" to figure out if any version is installable, or "composer require vladimir-yuldashev/laravel-queue-rabbitmq:^2.1" if you know which you need.

how can i fix this and install latest version ? 
Thanks for your patient.

**Comment by montazericollege** [comment]
we have same issue here !!

**Comment by Arthuralentejo** [comment]
Why this issue was closed? Did anyone find the solution?
