### ISSUE TITLE
laravel 9.42 is not compatible with laravel-queue-rabbitmq

### ISSUE THREAD

**Issue by amarmain** [vyuldashev/laravel-queue-rabbitmq#498]
- Laravel/Lumen version: 9.42
- RabbitMQ version: 3.11.2
- Package version: 13.0.1

Since laravel 9.42, the composer update command crashed.

Here's the error:

Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

at vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php:200

**Comment by bassem-shoukry** [comment]
Same issue

**Comment by amarmain** [comment]
duplicate with 499
