### ISSUE TITLE
PHP Fatal error:  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

### ISSUE THREAD

**Issue by Zdanc32** [vyuldashev/laravel-queue-rabbitmq#499]
I used command: 

composer update at laravel version 9.42

log:

`PHP Fatal error:  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null) in /home/gabriel/Projekty/subjects_and_grades/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php on line 200

   Symfony\Component\ErrorHandler\Error\FatalError 

  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

  at vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php:200
    196▕      *
    197▕      * @param  int  $status
    198▕      * @return int
    199▕      */
  ➜ 200▕     public function stop($status = 0): int
    201▕     {
    202▕         // Tell the server you are going to stop consuming.
    203▕         // It will finish up the last message and not send you any more.
    204▕         $this->channel->basic_cancel($this->consumerTag, false, true);

   Whoops\Exception\ErrorException 

  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

  at vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php:200
    196▕      *
    197▕      * @param  int  $status
    198▕      * @return int
    199▕      */
  ➜ 200▕     public function stop($status = 0): int
    201▕     {
    202▕         // Tell the server you are going to stop consuming.
    203▕         // It will finish up the last message and not send you any more.
    204▕         $this->channel->basic_cancel($this->consumerTag, false, true);

      +1 vendor frames 
  2   [internal]:0
      Whoops\Run::handleShutdown()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
`

**Comment by Zdanc32** [comment]
At version 9.39.0 still working

**Comment by joskfg** [comment]
This change produce the error https://github.com/laravel/framework/pull/45120

**Comment by Zdanc32** [comment]
ok, I will set version of laravel 9.39 and I will wait when lib use new   :P thanks anyway

Only what u need to do is add options to function stop() in Consumer class

    /**
     * Stop listening and bail out of the script.
     *
     * @param  int  $status
     * @return int
     */
    public function stop($status = 0, $options = null): int
    {
        // Tell the server you are going to stop consuming.
        // It will finish up the last message and not send you any more.
        $this->channel->basic_cancel($this->consumerTag, false, true);

        return parent::stop($status, $options);
    }

**Comment by bojcheski** [comment]
> ok, I will set version of laravel 9.39 and I will wait when lib use new :P thanks anyway
> 
> Only what u need to do is add options to function stop() in Consumer class
> 
> ```
> /**
>  * Stop listening and bail out of the script.
>  *
>  * @param  int
>  * @param  WorkerOptions|null  $options
>  * @return int
>  */
> public function stop($status = 0, $options = null): int
> {
>     // Tell the server you are going to stop consuming.
>     // It will finish up the last message and not send you any more.
>     $this->channel->basic_cancel($this->consumerTag, false, true);
> 
>     return parent::stop($status, $options);
> }
> ```

laravel 9.41.0 also works

**Comment by sturtond** [comment]
Is the pull request going live soon ?

**Comment by andrey-helldar** [comment]
Me too. Laravel `9.41.0` works, but `9.41.0-2` doesn't work.

**Comment by bojcheski** [comment]
> Is the pull request going live soon ?

just stick to laravel <= 9.41.0 until the pull request is merged. or if you really need laravel > 9.41 simply force vyuldashev/laravel-queue-rabbitmq not to be updated in your composer.json and adjust the code as it is in this pull request until everything is merged

**Comment by coloralp** [comment]
doesn't work with "laravel/framework": "^9.19",

**Comment by andrey-helldar** [comment]
@heylucasf, just run the `composer require laravel/framework:9.41` console command.

**Comment by heylucasf** [comment]
> 

In laravel/laravel project? (I am beginner)

**Comment by heylucasf** [comment]
> @heylucasf, just run the command and see

Worked, thanks.

**Comment by amarmain** [comment]
any update?

we have to use laravel 9.41 and cannot have the last laravel updated version because of this issue

**Comment by devzorg** [comment]
guys just make an override file
`"autoload": {
       "files": [
            "overrides/Consumer.php"
        ],`

**Comment by amarmain** [comment]
@devzorg thanks for the tip!

I've just test it and unlock laravel version updates in my composer

**Comment by gbespyatykh** [comment]
@devzorg thank you!

I will add little more details to your temporary solution to fix problem:

1. Copy `vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php` class to custom place. In my example is: `composer-overrides/vyuldashev/laravel-queue-rabbitmq/Consumer.php`.

2. Make signature and implementation compatible to parent in copied class:
```
    public function stop($status = 0, $options = null): int
    {
        $this->channel->basic_cancel($this->consumerTag, false, true);

        return parent::stop($status, $options);
    }
```

3. Update `autoload` section at root `composer.json`: exclude package's `Consumer` class from classmap. Next, add overriden class instead of them
```
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "exclude-from-classmap" : [
            "vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php"
        ],
        "files" : [
            "composer-overrides/vyuldashev/laravel-queue-rabbitmq/Consumer.php"
        ]
    },
```

4. Update laravel/framework package to latest version and dump autoloader's map:
`composer dump`


This solution tested with `php artisan queue:work` command

**Comment by geekyHomz** [comment]
Add to composer, the below line. It will downgrade the worker to be compatible with the package then once they fix the issue, remove it.

` "illuminate/queue": "9.41.0",`

**Comment by iamfarhad** [comment]
you can use my laravel rabbitmq package

https://github.com/iamfarhad/LaravelRabbitMQ

**Comment by zerossB** [comment]
Any solution for this?

I thought upgrading to version 13 of the package would work, but the same error happens in the same place.

```bash
 Symfony\Component\ErrorHandler\Error\FatalError

  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

  at vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php:200
    196▕      *
    197▕      * @param  int  $status
    198▕      * @return int
    199▕      */
  ➜ 200▕     public function stop($status = 0): int
    201▕     {
    202▕         // Tell the server you are going to stop consuming.
    203▕         // It will finish up the last message and not send you any more.
    204▕         $this->channel->basic_cancel($this->consumerTag, false, true);

      +26 vendor frames
  27  artisan:37
      App\Console\Kernel::handle("class Symfony\Component\Console\Input\ArgvInput { protected $definition = class Symfony\Component\Console\Input\InputDefinition { private array $arguments = [...]; private int $requiredCount = 0; private ?Symfony\Component\Console\Input\InputArgument $lastArrayArgument = NULL; private ?Symfony\Component\Console\Input\InputArgument $lastOptionalArgument = NULL; private array $options = [...]; private array $negations = [...]; private array $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = []; protected $interactive = TRUE; private array $tokens = [0 => 'package:discover', 1 => '--ansi']; private array $parsed = *uninitialized* }", "class Symfony\Component\Console\Output\ConsoleOutput { private int ${Symfony\Component\Console\Output\Output}verbosity = 32; private Symfony\Component\Console\Formatter\OutputFormatterInterface ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private bool $decorated = TRUE; private array $styles = [...]; private Symfony\Component\Console\Formatter\OutputFormatterStyleStack $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(2) of type (stream); private Symfony\Component\Console\Output\OutputInterface $stderr = class Symfony\Component\Console\Output\StreamOutput { private int ${Symfony\Component\Console\Output\Output}verbosity = 32; private Symfony\Component\Console\Formatter\OutputFormatterInterface ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter...")

  28  artisan:0
      {main}()

   Whoops\Exception\ErrorException

  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

  at vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php:200
    196▕      *
    197▕      * @param  int  $status
    198▕      * @return int
    199▕      */
  ➜ 200▕     public function stop($status = 0): int
    201▕     {
    202▕         // Tell the server you are going to stop consuming.
    203▕         // It will finish up the last message and not send you any more.
    204▕         $this->channel->basic_cancel($this->consumerTag, false, true);

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```

**Comment by M-Porter** [comment]
Hi, new maintainers were recently added and we are getting up to speed with going through issues and getting the library compatible again!

**Comment by samlay** [comment]
@M-Porter any ETA on merging? No rush, just so I know whether to wait or try out some of the suggested workarounds instead.

**Comment by M-Porter** [comment]
hey @samlay, hopefully by the end of the week. But I'm also moving on Saturday which means my free time it taken up by packing so please don't hold me to that 😅
