### ISSUE TITLE
php artisan rabbitmq:consume ket killed and make terminal stuck

### ISSUE THREAD

**Issue by anmolhesta** [vyuldashev/laravel-queue-rabbitmq#504]
### php artisan rabbitmq:consume get killed

I have setup the two laravel project and done all the things as mentioned [here](https://medium.com/geekculture/laravel-microservice-communication-using-rabbitmq-message-broker-9972927c6b3b) ,all the things work smoothly. But when i add custom job in setup-2 to read data sent from setup-1 as mentioned [here](https://medium.com/geekculture/laravel-microservice-communication-using-rabbitmq-message-broker-9972927c6b3b) php artisan rabbitmq:consume  sticks terminal for long time, and i ca't able to read the message published from setup-1.

Am i missing something here?
and if i comment payload function the i get this error 

> Call to a member function getBody() on null {"exception":"[object] (Error(code: 0): Call to a member function getBody() on null at /var/www/html/admin/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Jobs/RabbitMQJob.php:67)

 
### Setup-2 config/queue.php

> 

          'rabbitmq' => [

            'driver' => 'rabbitmq',
            'queue' => env('RABBITMQ_QUEUE', 'default'),
            'connection' => PhpAmqpLib\Connection\AMQPLazyConnection::class,

            'hosts' => [
                [
                    'host' => env('RABBITMQ_HOST', '127.0.0.1'),
                    'port' => env('RABBITMQ_PORT', 5672),
                    'user' => env('RABBITMQ_USER', 'guest'),
                    'password' => env('RABBITMQ_PASSWORD', 'guest'),
                    'vhost' => env('RABBITMQ_VHOST', '/'),
                ],
            ],

            'options' => [
                'ssl_options' => [
                    'cafile' => env('RABBITMQ_SSL_CAFILE', null),
                    'local_cert' => env('RABBITMQ_SSL_LOCALCERT', null),
                    'local_key' => env('RABBITMQ_SSL_LOCALKEY', null),
                    'verify_peer' => env('RABBITMQ_SSL_VERIFY_PEER', true),
                    'passphrase' => env('RABBITMQ_SSL_PASSPHRASE', null),
                ],
                'queue' => [
                    'job' => VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob::class,
                    // 'job' => App\Jobs\CustomHandleJob::class,
                    //'job' => App\Jobs\PingJob::class, ------------------------> this creates issue,commenting it work fine.
                ],
            ],

            /*
             * Set to "horizon" if you wish to use Laravel Horizon.
             */
            'worker' => env('RABBITMQ_WORKER', 'default'),

        ],

### PingJob in setup-2

> <?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;
use VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob as BaseJob;
//implements ShouldQueue

class PingJob extends BaseJob
{
    //use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
    }

    // public function fire()
    // {
    //     $payload = $this->payload();

    //     $class = WhatheverClassNameToExecute::class;
    //     $method = 'handle';

    //     $a = ($this->instance = $this->resolve($class))->{$method}($this, $payload);
    //     echo $payload;
    //     Log::info($payload);

    //     // $this->delete();
    // }

    /**
     * Get the decoded body of the job.
     *
     * @return array
     */
    public function payload()
    {
        Log::info($this->payload());
        // return [
        //     'job'  => '\App\Jobs\PingJob@handle',
        //     'data' => json_decode($this->getRawBody(), true)
        // ];
    }
}

**Comment by iamfarhad** [comment]
you can use of my laravel rabbitmq package

https://github.com/iamfarhad/LaravelRabbitMQ

**Comment by anmolhesta** [comment]
Issue has been resolved
