### ISSUE TITLE
doesn't work with mongodb

### ISSUE THREAD

**Issue by yktibrahim** [vyuldashev/laravel-queue-rabbitmq#505]
I tried the mongo db driver and it works fine, but when I try to consume it from the job I created with rabbitmq, it does not load data into mongodb and I get mongo db manager not found error.

**Comment by iamfarhad** [comment]
you can use my laravel rabbitmq package

https://github.com/iamfarhad/LaravelRabbitMQ

**Comment by yktibrahim** [comment]
> you can use my laravel rabbitmq package
> 
> https://github.com/iamfarhad/LaravelRabbitMQ

farhad thank you so much you are amazing mann thx

**Comment by M-Porter** [comment]
@yktibrahim This seems to be an issue with how your application is setup rather than an issue with the library itself. It's hard to really tell what is going on without knowing exactly how you are trying to access your database connection.
