### ISSUE TITLE
Laravel Illuminate\Queue\Worker::stop was changed in 9.47.0

### ISSUE THREAD

**Issue by IvanovPavel** [vyuldashev/laravel-queue-rabbitmq#507]
- Laravel/Lumen version: 9.47.0
- RabbitMQ version: #.#.#
- Package version: #.#.#

**Describe the bug**

PHP Fatal error:  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null) in /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php on line 200

**Steps To Reproduce**

`composer update`

**Expected behavior**

After composer update everything works as is

**Additional context**

CHANGE
VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int
TO
VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0, $options = null): int

**Comment by iamfarhad** [comment]
you can use my laravel rabbitmq package

https://github.com/iamfarhad/LaravelRabbitMQ

**Comment by shuqingzai** [comment]
See https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/502

**Comment by M-Porter** [comment]
Is resolved wit v13.1.0
