### ISSUE TITLE
Adding new maintainers?

### ISSUE THREAD

**Issue by khepin** [vyuldashev/laravel-queue-rabbitmq#510]
Hello @vyuldashev 

For starters, I'd like to tell you how much we appreciate the work that has gone into building this library to where it is today. I'm only one of the users but seeing the activity in issues and pull requests over the last couple months is a great indication of how many people rely on your work and thank you for it.

Since September of last year, there doesn't seem to have been much support for this project while questions have kept coming in and the latest available version is currently incompatible with Laravel's latest version. One user has reached the point where he made a fork and has posted it as the currently last answer to multiple PRs and issue threads.

I understand circumstances change and you might no longer be able or willing to maintain this package. **I wanted to know if you'd be open to adding new maintainers to this repo in order to keep it moving forward and help you with its maintenance.** I am happy to recommend some colleagues that have done great work with Laravel and RabbitMQ if you don't have anyone in mind.

Allowing this package to keep being useful would be a great gift to its community of users. Thank you for considering it.

**Comment by vyuldashev** [comment]
@khepin Hello, thank you for your kind works. Indeed, I'm no longer working daily with RabbitMQ. I am fully open to adding maintainers.

**Comment by khepin** [comment]
I've asked internally at work for people who would be interested. They all work on the daily with Rabbit MQ and Laravel. Looks like I can't tag them here for some reason. 
https://github.com/mattgrande
and
https://github.com/M-Porter
and myself @khepin would all be happy to help

You can reach all of us directly via laravel-rabbitmq [at] squareup.com if you'd like to discuss or establish guidance for the project.

Thank you

**Comment by vyuldashev** [comment]
Do you have telegram?

**Comment by khepin** [comment]
I do now. t.me/khepin

**Comment by iglazunoff** [comment]
@vyuldashev Hello!
I have an interest in working on this library. Laravel with RabbitMQ is my main stack. I'll be glad to participate)
My telegram & github @iglazunoff
