### ISSUE TITLE
Queue Failed

### ISSUE THREAD

**Issue by gutofurlan** [vyuldashev/laravel-queue-rabbitmq#514]
Good afternoon,
I have a laravel default job, but I need to inform Rabbit that it failed and it must send it to the failure queue, so that I can reprocess it in the future, how can I do it?
Thanks

My Job:
`class DefaultSendJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;`

thanks

**Comment by khepin** [comment]
You should look at the documentation in:
- https://laravel.com/docs/9.x/queues#max-job-attempts-and-timeout
- https://laravel.com/docs/9.x/queues#error-handling
- https://laravel.com/docs/9.x/queues#dealing-with-failed-jobs

This isn't specific to this library, just how Laravel handles it.
