### ISSUE TITLE
Bug install package

### ISSUE THREAD

**Issue by gutofurlan** [vyuldashev/laravel-queue-rabbitmq#519]
Hello, I'm installing the package but I'm having several compatibility errors,
I have use php 8.1.11
laravel 7.28.2

i am execute comand:
`docker-compose up -d rabbitmq`

I have this problem:
`
 Problem 1
    - Conclusion: don't install laravel/framework v7.29.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.29.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.29.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.29.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.30.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.30.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.30.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.30.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.30.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.30.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v7.30.6 (conflict analysis result)
    - vladimir-yuldashev/laravel-queue-rabbitmq[4.2, ..., v4.2.x-dev, 5.0, ..., v5.0.x-dev] require php-amqplib/php-amqplib 2.5.* -> satisfiable by php-amqplib/php-amqplib[v2.5.0, v2.5.1, v2.5.2].
    - vladimir-yuldashev/laravel-queue-rabbitmq[5.2, ..., v5.5.x-dev] require php-amqplib/php-amqplib 2.6.* -> satisfiable by php-amqplib/php-amqplib[v2.6.0, v2.6.1, v2.6.2, v2.6.3].
    - vladimir-yuldashev/laravel-queue-rabbitmq[v7.0.0, ..., v7.0.2] require illuminate/support 5.6.* -> satisfiable by illuminate/support[v5.6.0, ..., 5.6.x-dev].
    - php-amqplib/php-amqplib[v2.5.0, ..., v2.6.3] require ext-bcmath * -> it is missing from your system. Install or enable PHP's bcmath extension.
    - vladimir-yuldashev/laravel-queue-rabbitmq[v7.0.x-dev, ..., v7.5.0, v8.0.0, ..., v8.3.0] require php ^7.1.3 -> your php version (8.1.11) does not satisfy that requirement.
    - illuminate/support[v5.6.0, ..., 5.6.x-dev] require php ^7.1.3 -> your php version (8.1.11) does not satisfy that requirement.
    - vladimir-yuldashev/laravel-queue-rabbitmq[dev-feature/use-custom-job-class-v10, v9.0.0, ..., v9.1.2, v10.0.0, ..., v10.2.3] require php ^7.2 -> your php version (8.1.11) does not satisfy that requirement.
    - vladimir-yuldashev/laravel-queue-rabbitmq[dev-feature/abbility-to-hook-into-the-created-connection, dev-after-creating-connection-callback, v11.0.0, ..., v11.1.2] require php ^7.3 -> your php version (8.1.11) does not satisfy that requirement.
    - illuminate/queue[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.11) does not satisfy that requirement.
    - laravel/framework[v7.28.2, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.11) does not satisfy that requirement.
    - vladimir-yuldashev/laravel-queue-rabbitmq[dev-mporter/v13.1.0-release-notes, dev-master, v12.0.0, ..., v12.0.x-dev, v13.0.0, ..., v13.1.0] require illuminate/queue ^9.0 -> satisfiable by illuminate/queue[v9.0.0-beta.1, ..., 9.x-dev].
    - vladimir-yuldashev/laravel-queue-rabbitmq[v11.0.x-dev, ..., v11.3.0] require illuminate/queue ^8.0 -> satisfiable by illuminate/queue[v8.0.0, ..., 8.x-dev].
    - vladimir-yuldashev/laravel-queue-rabbitmq[v6.0.0, ..., v6.0.x-dev] require illuminate/support 5.5.* -> satisfiable by illuminate/support[v5.5.0, ..., 5.5.x-dev].
    - vladimir-yuldashev/laravel-queue-rabbitmq[5.1, ..., v5.1.x-dev] require illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, ..., 5.1.x-dev].
    - vladimir-yuldashev/laravel-queue-rabbitmq 4.1 requires illuminate/support 4.1.*@dev -> satisfiable by illuminate/support[v4.1.0, ..., 4.1.x-dev].
    - vladimir-yuldashev/laravel-queue-rabbitmq 4.0 requires illuminate/support 4.0.x -> satisfiable by illuminate/support[v4.0.0-BETA2, ..., 4.0.x-dev].
    - Only one of these can be installed: illuminate/queue[v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v7.28.2, ..., 7.x-dev]. laravel/framework replaces illuminate/queue and thus cannot coexist with it.
    - Only one of these can be installed: illuminate/support[dev-master, v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, 10.x-dev], laravel/framework[v7.28.2, ..., 7.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^7.28.2 -> satisfiable by laravel/framework[v7.28.2, ..., 7.x-dev].
    - Root composer.json requires vladimir-yuldashev/laravel-queue-rabbitmq * -> satisfiable by vladimir-yuldashev/laravel-queue-rabbitmq[dev-feature/use-custom-job-class-v10, dev-mporter/v13.1.0-release-notes, dev-feature/abbility-to-hook-into-the-created-connection, dev-master, dev-after-creating-connection-callback, 4.0, 4.1, 4.2, v4.2.x-dev, 5.0, ..., v5.5.x-dev, v6.0.0, ..., v6.0.x-dev, v7.0.0, ..., v7.5.0, v8.0.0, ..., v8.3.0, v9.0.0, ..., v9.1.2, v10.0.0, ..., v10.2.3, v11.0.0, ..., v11.3.0, v12.0.0, v12.0.1, v12.0.x-dev, v13.0.0, v13.0.1, 13.0.x-dev, v13.1.0].

To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sockets.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-bcmath` to temporarily ignore these required extensions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require vladimir-yuldashev/laravel-queue-rabbitmq:*" to figure out if any version is installable, or "composer require vladimir-yuldashev/laravel-queue-rabbitmq:^2.1" if you know which you need.

Installation failed, reverting ./composer.json to its original content.

`

Please what solution ? 
thanks

**Comment by khepin** [comment]
This package does not offer support for EOL versions of Laravel.
