### ISSUE TITLE
Suggestion for a replacement to PhpAmqpLib\Connection\AMQPLazyConnection

### ISSUE THREAD

**Issue by maxacarvalho** [vyuldashev/laravel-queue-rabbitmq#527]
Hello,

I just started using the package and noticed that the class `PhpAmqpLib\Connection\AMQPLazyConnection` is flagged as deprecated. I wonder if there's any considerations about what implementation to use instead?
Thanks.

**Comment by khepin** [comment]
Not at this time. The way to mark other connections as `lazy` is incompatible with how we create connections for now.

**Comment by behzadsh** [comment]
So would you please update the README? The configuration in README is so confusing.

**Comment by M-Porter** [comment]
@behzadsh you can always submit a PR to suggest fixes you think are needed.
