### ISSUE TITLE
Can't add a delay between consumption of messages.

### ISSUE THREAD

**Issue by gssj85** [vyuldashev/laravel-queue-rabbitmq#529]
- Laravel version: 10.3.2
- RabbitMQ version: 3.5.2
- Package version: 13.2.0

Using Laravel's Mail Facade I sent 10 emails to the emails queue.

`$email = (new TaskEventsMail($message, $subject))->onConnection('rabbitmq')->onQueue('emails');
        for ($i = 0; $i < 10; $i++) {
            Mail::to($to)->send($email);
        }`

When I try to consume with:

`php artisan rabbitmq:consume --rest 5 --queue emails`

The emails are processed without the delay of 5 seconds between each.

**Comment by adm-bome** [comment]
Because --rest option isn't implemented into the consumer `VladimirYuldashev\LaravelQueueRabbitMQ\Consumer:class`

This build in Consumer is made for high performance, so working with --rest is not the purpose of this worker.

**Tip 1:** 
>Try the laravel build in consumer on a rabbitmq connection and defined queue. See: ReadMe section Consuming messages.

**Tip2 :**
>Write your own consumer.

**Comment by gssj85** [comment]
I think it's misleading then having the option there...

Anyway I'm kinda lost on how to create a consumer following this package Laravel itself standards, only worked with Symfony and used a bore bones amqp, any guidance would be appreciated.

**Comment by khepin** [comment]
@adm-bome it's not implemented but I'm wondering if it should. The `rabbitmq:consume` command extends the `queue:work` one so it might be reasonable to implement all options from `queue:work` on `rabbitmq:consume`.
I'll re-open it for now so I can take a look later

**Comment by adm-bome** [comment]
Sure we can implement it. No problem just 3 lines of code :wink: 

But (my opinion) adding a delay (sleep) to this worker, the purpose of this consumer will become some what blurry and you can just use the `queue:work` command. 

`basic_consume` does not work the same as `basic_get`. (not everything is possible)

**Comment by khepin** [comment]
PR with my thoughts for why we should consider respecting it https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/530

**Comment by gssj85** [comment]
I got the delay I wanted this way:

1. Created a CustomMailJob class that extends SendQueueMailable
2. Overwrited the method handle() and before calling parent::handle() added a sleep(5)
3. In the Mailable class overwrited the method newQueueJob() and where it called SendQueuedMailable class, changed to the CustomMailJob class created.

It worked, by far the most deep I have gone into OO in my whole (short) carrer in programming haha.

About the terminal command parameter I was thinking about just removing that from the --help and I was happy that maybe I could do that and contribute. :smiley:
