### ISSUE TITLE
Spam queue when rabbitmq error

### ISSUE THREAD

**Issue by dwiyudirayia** [vyuldashev/laravel-queue-rabbitmq#533]
Chronology : I have endpoint to trigger queue, when hit the endpoint that queue keep spamming all the time. When i check rabbitmq logs `client unexpectedly closed TCP connection` and `closing AMQP connection` but that case sometimes it happens

**Comment by khepin** [comment]
I'm sorry but I don't really understand what you're saying. We'll need more details in order to help in any sort of way here. I'm closing the issue for now as there is insufficient info for us to help, but feel free to re-open if you add something.
