### ISSUE TITLE
 job status stocks in pending

### ISSUE THREAD

**Issue by mawebcoder** [vyuldashev/laravel-queue-rabbitmq#537]
- Laravel:10

- Package version: 13.2

Suppose we have two servers, in each of one Laravel Horizon is serving a queue that the name of the queues are difference. The producer dispatches a job, but the job is executed in the consumer who serves this queue (in the environment of the first dispatch server and In the second server environment, its handle method is executed) the producer enters the job correctly into the queue in RabbitMQ and the consumer also executes the job correctly. But the job remains pending in the laravel horizon of the  producer and not in the consumption The producer and not in the producer is not placed in the completed state while the job is consumed on the consumer side. I expect that the job in the producer or consumer will change to the completed state in the horizon.

**Comment by khepin** [comment]
The issue description isn't legible to me and I cannot make sense of it in its current state.
Please add details potentially some diagrams could be helpful too.

Also, can you confirm that this issue is specific to rabbitmq and would not happen with a different queue driver?

**Comment by adm-bome** [comment]
I think you are using diffrent databases for Redis (Publishing server and the Consuming server use there own Redis instance and databases)

Horizon is dependend of events fired within Redis. 

Try to use the same Redis Server.

Your Publishing server and your Consuming Server will both register against the same events and will update accordingly.

**Comment by adm-bome** [comment]
closed due to inactivity

_please re-open when there is still issue._
