### ISSUE TITLE
Doubt about multiple workers

### ISSUE THREAD

**Issue by juizmill** [vyuldashev/laravel-queue-rabbitmq#539]
I would like to know if this LIB works with several machines running the same worker without repeating the process on different machines.

For example: I have 3 machines running the workers and I don't want the data from queue number 1 to be processed again in machine 2.

Is there any configuration to avoid this duplicate execution on several machines running the same worker

**Comment by khepin** [comment]
This will work exactly as you want. A queue will receive n jobs `[J1 .... Jn]` and each worker will pull some jobs from the queue and work on them. When a worker W1 has hold of the jobs `[J1, J2, J3]`, no other worker `[W2 ... Wm]` can see those jobs `[J1, J2, J3]`.
Only in the case that `W1` fails at processing `J1` will `J1` be returned to the queue and might then get processed by a new worker `W2`. But at that point, `W1` would no longer be seeing `J1` nor would it be working on it.

**Comment by adm-bome** [comment]
closed: extensive explanation by  @khepin
