### ISSUE TITLE
offtopic: when 13.3.0 will be released ?

### ISSUE THREAD

**Issue by oprudkyi** [vyuldashev/laravel-queue-rabbitmq#541]
Hi, 

master includes many important updates and we postponed update to laravel 10 till 13.3 release
but it seems nearly month passed after latest changes 

I'm hoping everything fine

**Comment by adm-bome** [comment]
Offcourse,

I prepaired this lib for release [v13.3.0](https://github.com/vyuldashev/laravel-queue-rabbitmq/releases/tag/untagged-8d20c8f46d16c86e9ca4)

Most changes were done by me. As i do feel confident, everything is working as it should. I didnt find myself in a place, to release my own work. ( It's like getting the butcher to inspect his own meat.)

I was hoping someone was picking up on this, and continue with a release. @khepin @M-Porter @vyuldashev 

The last month, people were able to test the master. Hopefully they did.... 
A release will follow by the end of this month.

**Comment by khepin** [comment]
Agree that this is now in place for a release. I'll get to it tomorrow.

**Comment by khepin** [comment]
done
