### ISSUE TITLE
PHP 8.1 Compatibility issues

### ISSUE THREAD

**Issue by bostin** [vyuldashev/laravel-queue-rabbitmq#544]
- Laravel/Lumen version: 10.12.0
- Package version: 13.3.0

**Describe the bug**

Typed property VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::$currentJob must not be accessed before initialization 

**Steps To Reproduce**

using php8.1

**Comment by bostin** [comment]
13.2.0 is ok

**Comment by khepin** [comment]
#543

**Comment by khepin** [comment]
Fixed in v13.3.1
