### ISSUE TITLE
All jobs are added to the default queue

### ISSUE THREAD

**Issue by durmusunsst** [vyuldashev/laravel-queue-rabbitmq#547]
- Laravel/Lumen version: 9.19
- RabbitMQ version: 3.11.11
- Package version: 13.3.1

**Describe the bug**

All jobs are added to the default queue. Queue definitions in Laravel jobs are ignored.

**Comment by khepin** [comment]
Without a clearer description and more details on how you have things setup, there is really nothing we can do to help you. Closing this until there are sufficient details.
