### ISSUE TITLE
Job Batching: cannot use a specific queue

### ISSUE THREAD

**Issue by amarmain** [vyuldashev/laravel-queue-rabbitmq#548]
- Laravel/Lumen version: 9.52.9
- RabbitMQ version: 3.11.2
- Package version: 13.3.1

**Describe the bug**

When I try to use job batching in a specific queue (https://laravel.com/docs/9.x/queues#batch-connection-queue), jobs are executed in default queue.

Maybe linked with this issue? https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/547

**Steps To Reproduce**

If I try to run these code:

$batch = Bus::batch([new MyJob])->onQueue('myqueue')->dispatch();

The job is sent to default queue instead of myqueue.

I have to rollback to 13.2.* package version to correct it.

**Comment by qq2161811** [comment]
![image](https://github.com/vyuldashev/laravel-queue-rabbitmq/assets/31003386/1eb913bf-051f-474d-a1ed-a5a15347576f)
The passed parameters are messed up in the bulk method call publishBatch, my God, it makes me very headache.

**Comment by adm-bome** [comment]
Nice catch. Realy how¿

**Comment by adm-bome** [comment]
Will correct this tomorrow if i see some time

**Comment by durmusunsst** [comment]
yes i tried to express this exact problem
