### ISSUE TITLE
[BUG] VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue::$lastPushed not initialization

### ISSUE THREAD

**Issue by shuqingzai** [vyuldashev/laravel-queue-rabbitmq#551]
- Laravel/Lumen version:
```bash
php artisan --version
Laravel Framework 9.52.9
```
- RabbitMQ version: 
```bash
3.10
```

- Package version: 
```bash
composer show vladimir-yuldashev/laravel-queue-rabbitmq

name     : vladimir-yuldashev/laravel-queue-rabbitmq
descrip. : RabbitMQ driver for Laravel Queue. Supports Laravel Horizon.
keywords :
versions : * 13.3.2
```

**Describe the bug**

`VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue::$lastPushed` has added type, but it is not initialized, resulting in an error when using `\VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue::pushRaw()`

See: [src/Horizon/RabbitMQQueue.php](https://github.com/vyuldashev/laravel-queue-rabbitmq/commit/f2f7a5e7a907ad2bb39fe0113add5220ead82338#diff-6f4a5e52fb691c0f2d299984cf5db15896c8ada5c806e10cb50be3bba56691db)

error: 

```log
Typed property VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue::$lastPushed must not be accessed before initialization
```

**Steps To Reproduce**

Call `\VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue::pushRaw()` to send messages or use the Horizon dashboard to retry failed tasks

**Current behavior**

- What happens with the worker?
- Is the message retried or put back into the queue?
- Is the message acknowledged or rejected?
- Is the message unacked?
- Is the message gone?

**Expected behavior**

What is the expected behavior

**Additional context**

Add any other context about the problem or describe the use-case.

**Comment by Franpanozzo** [comment]
Hello, if this can be fixed it will be great! we're having the same issue
