### ISSUE TITLE
The "verify_peer" is not working correctly.

### ISSUE THREAD

**Issue by durmusunsst** [vyuldashev/laravel-queue-rabbitmq#557]
The "verify_peer" is not working correctly.

The following line of code in the "src/Queue/Connection/ConfigFactory.php" file:

if ($verifyPeer = Arr::get($sslConfig, 'verify_peer')) {
$connectionConfig->setSslVerify($verifyPeer);
}

should be changed as follows:

$verifyPeer = Arr::get($sslConfig, 'verify_peer');

if ($verifyPeer !== null) {
$connectionConfig->setSslVerify($verifyPeer);
}

Because if a user sets the "verify_peer" value to false in the config, it will not enter the if block and "verify_peer" will always be null. This causes the SSL settings to not work correctly. I haven't contributed, so I couldn't send a fix. Could you make this change in the current version? We really need this fix right now.

**Comment by khepin** [comment]
Looking into this

**Comment by khepin** [comment]
https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/558
Can you please try the `verifypeer` branch and report back whether that works as expected.

**Comment by durmusunsst** [comment]
@khepin 

#558 is working correctly

**Comment by adm-bome** [comment]
As PR #570 was merged
