### ISSUE TITLE
Delayed queues as type quorum queue

### ISSUE THREAD

**Issue by TomKeur** [vyuldashev/laravel-queue-rabbitmq#563]
First, let me say thank you for this great package!

We're using Delayed queues, the queues are created by this package and also disappear when they are not needed anymore, this is all working fine!

Some of our queues, will delay messages for a couple of days, for example: When an external service is down.
I saw that that created `default.delay.xyz` queues, are of the type `classic`.

Is it Possible to use the configuration option if quorum enabled?
It's a really small change in the `getDelayQueueArguments`, so I've created a PR.

**Comment by adm-bome** [comment]
See conversation in the PR #564

Queues created for delaying messages won't profit from quorum settings.
