### ISSUE TITLE
How to connect to amqps?

### ISSUE THREAD

**Issue by SerikK** [vyuldashev/laravel-queue-rabbitmq#565]
I am wondering if this library can connect to amqps? I think it is rabbitmq aws

Currently I have `Invalid frame type 21` error

**Comment by SerikK** [comment]
I set secure => true and network_protocol => ssl and it worked

**Comment by TienLuatNguyen** [comment]
Nice! ;)

**Comment by zerossB** [comment]
@TienLuatNguyen @SerikK 
Can you provide an example to solve this problem?
