### ISSUE TITLE
Channel connection is closed with multiple instances.

### ISSUE THREAD

**Issue by antomarsi** [vyuldashev/laravel-queue-rabbitmq#567]
- Laravel: 8
- Package version: 11.3

Currently i'm facing a problem with lot of messages of "Channel connection is closed.", from my team, Devops mentioned that looks like even if we add more instances of the server that run the `php artisan queue:work --queue=<queue name>`, we still have only one queue working over some period of time. Do someone faced the same problem? Or know if something is wrong?

**Comment by khepin** [comment]
Not sure I understand this fully. Looks like there are multiple issues here:

- `Channel connection is closed` do those happen on publish or on consume? If on publish, you should reconnect and retry. If on consume, ideally you let the queue worker fail and restart entirely.
On more recent versions, we attempt reconnects directly in the package, so consider upgrading too.
- What you mention about `we still have only one queue working over some period of time` I don't understand and can't help you without more details.

**Comment by adm-bome** [comment]
for some help...

workers should work. i believe laravel has options to instruct workers to die, when they run for too long or have no messages for a period of time.
php was not ment to run for long processes so you have to find a solution to let the workers die gracefully.

RabbitMQ closses connections automaticaly when there was no communication on the open connection. so probably nothing to do with this lib. (but with laravel eco system or with the config in rabbitMQ.

As a side node: with horizon  in place a manager controles the workers  and make sure a new worker was created with a new connection when the old worker dies.

**Comment by adm-bome** [comment]
closed: without further explanation of the issue or indication this issue is related to this library.
