### ISSUE TITLE
We were running with Laravel 8 in kubernetes . But lots of connection is being created without closing old connection. Connection string having different port overtime.

### ISSUE THREAD

**Issue by Kibria7533** [vyuldashev/laravel-queue-rabbitmq#568]
- Laravel/Lumen version: #.#.#
- RabbitMQ version: #.#.#
- Package version: #.#.#

**Describe the bug**

**Steps To Reproduce**

What steps needed, to reproduce this bug.

**Current behavior**

- What happens with the worker?
- Is the message retried or put back into the queue?
- Is the message acknowledged or rejected?
- Is the message unacked?
- Is the message gone?

**Expected behavior**

What is the expected behavior

**Additional context**

Add any other context about the problem or describe the use-case.

**Comment by khepin** [comment]
I don't know what to do with this report. Please open a detailed report instead of a single sentence in the issue title if you actually need help.
