### ISSUE TITLE
No connector for [rabbitmq] with Laravel 10

### ISSUE THREAD

**Issue by rayan2014** [vyuldashev/laravel-queue-rabbitmq#569]
- Laravel version: ^10.10
- RabbitMQ version: using cloudamqp
- Package version: ^13.3

I have already installed this package on a fresh larvel with above version and i got it to work, but when it comes to install it on old project also with same information above i got error
No connector for [rabbitmq].

i tried to clear cache 
php artisan config:clear
php artisan optimize:clear

this is my config/queue.php
'rabbitmq' => [

            'driver' => 'rabbitmq',
            'hosts' => [
                [
                    'host' => env('RABBITMQ_HOST', '127.0.0.1'),
                    'port' => env('RABBITMQ_PORT', 5672),
                    'user' => env('RABBITMQ_USER', 'guest'),
                    'password' => env('RABBITMQ_PASSWORD', 'guest'),
                    'vhost' => env('RABBITMQ_VHOST', '/'),
                ],
                // ...
            ],

        ],
but the problem  still blocking me.

```
PS G:\Projects\90soft\Sales\pill-store-landlord-backend> php artisan optimize:clear
PHP Warning:  Module "sockets" is already loaded in Unknown on line 0

Warning: Module "sockets" is already loaded in Unknown on line 0

   InvalidArgumentException 

  No connector for [rabbitmq].

    181▕         return call_user_func($this->connectors[$driver]);
    182▕     }

  1   vendor\laravel\framework\src\Illuminate\Queue\QueueManager.php:162
      Illuminate\Queue\QueueManager::getConnector("rabbitmq")

  2   vendor\laravel\framework\src\Illuminate\Queue\QueueManager.php:138
      Illuminate\Queue\QueueManager::resolve("rabbitmq")


```

any other information to let you know i will be happy to provide you with.

**Comment by rayan2014** [comment]
@vyuldashev
@jeromegamez 
@benperiton 
@mintopia 
please help

**Comment by rayan2014** [comment]
this is my composer.json
"require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "intervention/image": "^2.7",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "saloonphp/saloon": "^2.9",
        "sammyjo20/saloon": "^2.8",
        "spatie/laravel-multitenancy": "^3.0",
        "spatie/laravel-permission": "^5.10",
        "vladimir-yuldashev/laravel-queue-rabbitmq": "^13.3"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laracademy/generators": "^3.6",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },

**Comment by adm-bome** [comment]
`MultitenancyServiceProvider::class` should be loaded **after** `LaravelQueueRabbitMQServiceProvider::class`.

Disable the auto discovery in the composer.json file
```json

  "extra": {
      "laravel": {
          "dont-discover": [
              "spatie/laravel-multitenancy",
              "vladimir-yuldashev/laravel-queue-rabbitmq"
          ]
      }
  },

```


Add provider(s) manually to /config/app.php. RabbitMQ has to be before Multitenancy.
```php
// file: config/app.php

   //...

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        //...

        /*
         * 3th Party - Package Service Providers...
         */
        VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider::class,
        Spatie\Multitenancy\MultitenancyServiceProvider::class,

        /*
         * Application Service Providers...
         */
        //...
    ],

```

after the change run: `composer install` or `composer dump-autoload`.
