### ISSUE TITLE
Undefined array key "uuid" for custom Job class

### ISSUE THREAD

**Issue by akalongman** [vyuldashev/laravel-queue-rabbitmq#571]
Laravel 10

In my application, I am processing jobs from other non-laravel projects, so messages from rabbitmq have raw json structure. To handle this, I've created a custom job class with a method `payload()`:
```php
public function payload(): array
{
    $data = parent::payload();

    if (isset($data['job'])) {
        return $data;
    }

    $command = new MyCustomCommand($data); 

    return [
        'uuid'          => Str::uuid()->toString(),
        'displayName'   => $command::class,
        'job'           => 'Illuminate\Queue\CallQueuedHandler@call',
        'maxTries'      => null,
        'maxExceptions' => null,
        'failOnTimeout' => false,
        'backoff'       => null,
        'timeout'       => null,
        'retryUntil'    => null,
        'data'          => [
            'commandName' => $command::class,
            'command'     => serialize($command),
        ],
    ];
}
```

When the job fails, I have the following exception: `Undefined array key "uuid" in /vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseUuidFailedJobProvider.php on line 59`

How can I solve this bug?

**Comment by khepin** [comment]
At first glance, this issue doesn't seem to come from this library but to be between your code and Laravel so I'll be closing it.
If there is additional information as to why there is an issue in this library, feel free to re-open.

**Comment by matiazar** [comment]
> Laravel 10
> 
> In my application, I am processing jobs from other non-laravel projects, so messages from rabbitmq have raw json structure. To handle this, I've created a custom job class with a method `payload()`:
> 
> ```
> public function payload(): array
> {
>     $data = parent::payload();
> 
>     if (isset($data['job'])) {
>         return $data;
>     }
> 
>     $command = new MyCustomCommand($data); 
> 
>     return [
>         'uuid'          => Str::uuid()->toString(),
>         'displayName'   => $command::class,
>         'job'           => 'Illuminate\Queue\CallQueuedHandler@call',
>         'maxTries'      => null,
>         'maxExceptions' => null,
>         'failOnTimeout' => false,
>         'backoff'       => null,
>         'timeout'       => null,
>         'retryUntil'    => null,
>         'data'          => [
>             'commandName' => $command::class,
>             'command'     => serialize($command),
>         ],
>     ];
> }
> ```
> 
> When the job fails, I have the following exception: `Undefined array key "uuid" in /vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseUuidFailedJobProvider.php on line 59`
> 
> How can I solve this bug?

@akalongman did you solve this?

**Comment by akalongman** [comment]
Not yet 😐

**Comment by matiazar** [comment]
I dont understand all the process but I think like is calling payload function lot of times.. and each time it generates a new uuid... its throwing this error. but I need to research a little more

**Comment by akalongman** [comment]
Looks like this happens, when a job fails and Laraver tries to reprocess the job (--tries=3 flag). But its very difficult to debug :(

**Comment by matiazar** [comment]
I need to fix this because some jobs are failing but I cant see any log.. and failed jobs table is not filled.

**Comment by matiazar** [comment]
@akalongman I fixed this.. try to add this function on your RabbitMQJob

  ```
  public function getRawBody(): string
    {
        $body = $this->message->getBody();
        if ($this->isLaravelJob($body)) return $body;

        $parent_function_name = debug_backtrace()[1]['function'];
        if ($parent_function_name == "logFailedJob") {
            return json_encode($this->payload());
        }

        return $body;
    }

    private function isLaravelJob($data){
        if (APIHelper::isJson($data)) $data = json_decode($data, true);
        if (isset($data['data']) && isset($data['data']['commandName']) && isset($data['data']['command'])) return true;
        return false;
    }
```

**Comment by akalongman** [comment]
@matiazar after few months, can you confirm that your solution is working?
