### ISSUE TITLE
allow laravel to end workers with lost connection - laravel 8 and php ^7.3

### ISSUE THREAD

**Issue by urosZoretic** [vyuldashev/laravel-queue-rabbitmq#576]
- Laravel: 8
- php: 7.3
- RabbitMQ version: 0.9.0
- Package version: 11.3.0

**Describe the bug**

worker not being stopped after rbmq connection lost

connected issue:
[457](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/457)

fix is included in package version 12.0.1 which needs php version 8, but is currently not an option for me.

**Steps To Reproduce**

* laravel project version 8 with php 7.3 nad package version 11.3.0. 
* start laravel queue worker ` ./artisan queue:work`
* disconnect rabbitmq server
* worker is not stopped

**Current behavior**

worker not being stopped after rbmq connection lost

**Expected behavior**

worker should be stopped.

**Fix**

can you add PR [457](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/457) fix also to package version 11.* as an fix version 11.3.1. Then I can update my laravel  project withoud my own workarounds

**Comment by khepin** [comment]
PR is merged in maintained versions.
