### ISSUE TITLE
Was this package abandoned?

### ISSUE THREAD

**Issue by durmusunsst** [vyuldashev/laravel-queue-rabbitmq#578]
Very important pull requests have not been merged for a long time. If this package is abandoned, people should be directed to use different alternatives. It looks like they are not maintained.

**Comment by khepin** [comment]
Which PR are you looking at? There is a new set of maintainers since about a year ago.

**Comment by durmusun** [comment]
newverifypeer

**Comment by durmusun** [comment]
Correctly handle Verify Peer option #570 @khepin

**Comment by khepin** [comment]
My bad. That one escaped me, it's in the latest release now.

**Comment by durmusun** [comment]
Thank you @khepin
