### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by DaaN88** [vyuldashev/laravel-queue-rabbitmq#584]
- Laravel/Lumen version: #.#.#
- RabbitMQ version: #.#.#
- Package version: #.#.#

**Describe the bug**

vladimir-yuldashev/laravel-queue-rabbitmq[v13.3.0, ..., v13.3.5] require illuminate/queue ^9.0|^10.0 -> satisfiable by illuminate/queue[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.1].

**Steps To Reproduce**

composer update after change version Laravel

**Additional context**

please add Laravel 11 support :-)

**Comment by khepin** [comment]
https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/585 initial PR
Waiting on support from testbench: https://github.com/orchestral/testbench/issues/397

**Comment by lv2u** [comment]
@vyuldashev Any chance we can get this merged soon?

**Comment by toshderv** [comment]
> #585 initial PR Waiting on support from testbench: [orchestral/testbench#397](https://github.com/orchestral/testbench/issues/397)

Completed

**Comment by tebbbb** [comment]
for the impatient people, you can composer require tebbbb/laravel-queue-rabbitmq which has the version changes of this PR included. My package will be removed, once this package is updated.

**Comment by dimonets** [comment]
> should have this merged today

Impatiently waiting... Thanks
