### ISSUE TITLE
not support "Use your own RabbitMQJob class" 

### ISSUE THREAD

**Issue by huangbule2024** [vyuldashev/laravel-queue-rabbitmq#592]
- Laravel/Lumen version: 8.83.27
- RabbitMQ version: 1.51
- Package version: "vladimir-yuldashev/laravel-queue-rabbitmq": "11",

**Describe the bug**

not support "Use your own RabbitMQJob class" 
`'queue' => [
                'job' => \App\Queue\Jobs\RabbitMQJob::class,
],`

**Steps To Reproduce**

RabbitMQQueue  pop  method  currentJob not get from  queue.php job property

![image](https://github.com/vyuldashev/laravel-queue-rabbitmq/assets/91714264/6a888333-ce96-4ac9-99e6-434d64398848)

**Comment by mehrmudi** [comment]
Thanks for flagging that issue! Glad to hear it’s fixed now in **[this pull request](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/370)**.  If you haven't already upgraded your dependency, I recommend upgrading to the latest version to ensure you have all the latest features and fixes.
